<a href="https://colab.research.google.com/github/abhishekwanave/abhishek/blob/main/AI_Travel_Planner_FIRST_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
import pandas as pd
import json
import numpy

In [4]:
# Load Attractions Dataset
with open("nashik_tourist_attractions_final.json") as f:
    attractions = json.load(f)

# Load Food Dataset
with open("nashik_food_final_v2.json") as f:
    food = json.load(f)

# Load Transport Dataset
with open("nashik_transport_final.json") as f:
    transport = json.load(f)

# Load Hotels Dataset
with open("nashik_hotels_final.json") as f:
    hotels = json.load(f)

print("Datasets loaded successfully")

Datasets loaded successfully

In [5]:
print("Number of attractions:", len(attractions))
print("Number of food places:", len(food))
print("Number of transport options:", len(transport))
print("Number of hotels:", len(hotels))

Number of attractions: 20
Number of food places: 20
Number of transport options: 34
Number of hotels: 20

In [6]:
print(attractions[0])

{'id': 'trimbakeshwar_temple', 'name': 'Trimbakeshwar Temple', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 200, 'avg_visit_time_hours': 2.0, 'experience_score': 10, 'location_area': 'Trimbak', 'distance_from_nashik_city_km': 28, 'travel_time_from_cbs_minutes': 55, 'best_time_to_visit': 'Morning', 'crowd_level': 'High', 'route_cluster': 'Trimbakeshwar Route', 'route_order': 3, 'accessibility_score': 5, 'food_available_nearby': True, 'transport_modes': ['bus', 'cab', 'private'], 'fatigue_cost': 3, 'indoor_outdoor': 'Both', 'weather_sensitivity': False, 'traffic_sensitivity': 'High', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 400, 'opening_hours': '05:30–21:00', 'nearby_attractions': ['brahmagiri_hills', 'anjaneri_hills'], 'parking_available': True, 'photography_allowed': False, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '06:00', 'description': 'One of the twelve Jyotirlingas of Lord Shiva, Trimbakeshwar Temple is a sacred pilgrimage site nestled at the foot of Brahmagiri Hills. The temple is renowned for its unique three-faced Shivalinga representing Brahma, Vishnu, and Shiva.', 'visitor_rating': 4.7, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Trimbakeshwar_temple.jpg/640px-Trimbakeshwar_temple.jpg'}

In [7]:
import json
print(json.dumps(attractions[0], indent=4))

{
    "id": "trimbakeshwar_temple",
    "name": "Trimbakeshwar Temple",
    "category": "Spiritual",
    "entry_fee": 0,
    "vip_fee": 200,
    "avg_visit_time_hours": 2.0,
    "experience_score": 10,
    "location_area": "Trimbak",
    "distance_from_nashik_city_km": 28,
    "travel_time_from_cbs_minutes": 55,
    "best_time_to_visit": "Morning",
    "crowd_level": "High",
    "route_cluster": "Trimbakeshwar Route",
    "route_order": 3,
    "accessibility_score": 5,
    "food_available_nearby": true,
    "transport_modes": [
        "bus",
        "cab",
        "private"
    ],
    "fatigue_cost": 3,
    "indoor_outdoor": "Both",
    "weather_sensitivity": false,
    "traffic_sensitivity": "High",
    "group_suitability": [
        "solo",
        "couple",
        "family",
        "group"
    ],
    "avg_cost_per_person": 400,
    "opening_hours": "05:30\u201321:00",
    "nearby_attractions": [
        "brahmagiri_hills",
        "anjaneri_hills"
    ],
    "parking_available": true,
    "photography_allowed": false,
    "seasonal_availability": "Year-round",
    "family_friendly": true,
    "typical_visit_start_time": "06:00",
    "description": "One of the twelve Jyotirlingas of Lord Shiva, Trimbakeshwar Temple is a sacred pilgrimage site nestled at the foot of Brahmagiri Hills. The temple is renowned for its unique three-faced Shivalinga representing Brahma, Vishnu, and Shiva.",
    "visitor_rating": 4.7,
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Trimbakeshwar_temple.jpg/640px-Trimbakeshwar_temple.jpg"
}

In [8]:
len(attractions)

20

In [9]:
attractions_df = pd.DataFrame(attractions)

attractions_df.head()

,id,name,category,entry_fee,vip_fee,avg_visit_time_hours,experience_score,location_area,distance_from_nashik_city_km,travel_time_from_cbs_minutes,...,opening_hours,nearby_attractions,parking_available,photography_allowed,seasonal_availability,family_friendly,typical_visit_start_time,description,visitor_rating,image_url
0,trimbakeshwar_temple,Trimbakeshwar Temple,Spiritual,0,200,2.00,10,Trimbak,28.0,55,...,05:30–21:00,"[brahmagiri_hills, anjaneri_hills]",True,False,Year-round,True,06:00,"One of the twelve Jyotirlingas of Lord Shiva, ...",4.7,https://upload.wikimedia.org/wikipedia/commons...
1,ramkund,Ramkund,Spiritual,0,0,1.00,9,Panchavati,3.0,10,...,05:00–21:00,"[kalaram_temple, navshya_ganpati, sita_gumpha]",False,True,Year-round,True,06:00,Ramkund is a sacred bathing tank on the banks ...,4.5,https://upload.wikimedia.org/wikipedia/commons...
2,kalaram_temple,Kalaram Temple,Spiritual,0,0,1.00,9,Panchavati,3.0,10,...,05:30–21:30,"[ramkund, navshya_ganpati, sita_gumpha]",False,False,Year-round,True,06:30,Kalaram Temple is one of the most important Hi...,4.6,https://upload.wikimedia.org/wikipedia/commons...
3,navshya_ganpati,Navshya Ganpati Temple,Spiritual,0,0,0.75,7,Panchavati,3.0,12,...,06:00–21:00,"[kalaram_temple, ramkund, sita_gumpha]",False,True,Year-round,True,07:00,Navshya Ganpati is a beloved Ganesh temple in ...,4.3,https://www.google.com/search?tbm=isch&q=Navsh...
4,sita_gumpha,Sita Gumpha (Sita's Cave),Spiritual,0,0,0.50,7,Panchavati,3.5,12,...,06:00–18:00,"[kalaram_temple, ramkund, navshya_ganpati]",False,True,Year-round,True,07:30,Sita Gumpha is a small cave shrine in Panchava...,4.1,https://upload.wikimedia.org/wikipedia/commons...

In [10]:
attractions_df.columns

Index(['id', 'name', 'category', 'entry_fee', 'vip_fee',
       'avg_visit_time_hours', 'experience_score', 'location_area',
       'distance_from_nashik_city_km', 'travel_time_from_cbs_minutes',
       'best_time_to_visit', 'crowd_level', 'route_cluster', 'route_order',
       'accessibility_score', 'food_available_nearby', 'transport_modes',
       'fatigue_cost', 'indoor_outdoor', 'weather_sensitivity',
       'traffic_sensitivity', 'group_suitability', 'avg_cost_per_person',
       'opening_hours', 'nearby_attractions', 'parking_available',
       'photography_allowed', 'seasonal_availability', 'family_friendly',
       'typical_visit_start_time', 'description', 'visitor_rating',
       'image_url'],
      dtype='object')

In [11]:
attractions_df[["name","experience_score","entry_fee"]].head()

                        name  experience_score  entry_fee
0       Trimbakeshwar Temple                10          0
1                    Ramkund                 9          0
2             Kalaram Temple                 9          0
3     Navshya Ganpati Temple                 7          0
4  Sita Gumpha (Sita's Cave)                 7          0

In [12]:
print(attractions_df.columns)

Index(['id', 'name', 'category', 'entry_fee', 'vip_fee',
       'avg_visit_time_hours', 'experience_score', 'location_area',
       'distance_from_nashik_city_km', 'travel_time_from_cbs_minutes',
       'best_time_to_visit', 'crowd_level', 'route_cluster', 'route_order',
       'accessibility_score', 'food_available_nearby', 'transport_modes',
       'fatigue_cost', 'indoor_outdoor', 'weather_sensitivity',
       'traffic_sensitivity', 'group_suitability', 'avg_cost_per_person',
       'opening_hours', 'nearby_attractions', 'parking_available',
       'photography_allowed', 'seasonal_availability', 'family_friendly',
       'typical_visit_start_time', 'description', 'visitor_rating',
       'image_url'],
      dtype='object')

In [13]:
# Attraction Scoring Engine

def fatigue_to_number(fatigue):

    if fatigue == "low":
        return 1
    elif fatigue == "medium":
        return 2
    elif fatigue == "high":
        return 3
    else:
        return 2


def calculate_scores(attractions):

    scored_attractions = []

    experience_weight = 5
    fatigue_weight = 2
    time_weight = 1
    cost_weight = 1

    for place in attractions:

        experience = place.get("experience_score", 5)

        fatigue = fatigue_to_number(place.get("fatigue_level", "medium"))

        visit_time = place.get("avg_visit_time_hours", 1)

        cost = place.get("entry_fee", 0)

        score = (
            experience_weight * experience
            - fatigue_weight * fatigue
            - time_weight * visit_time
            - cost_weight * cost
        )

        place["priority_score"] = score

        scored_attractions.append(place)

    return scored_attractions


def sort_attractions(scored_attractions):

    sorted_places = sorted(
        scored_attractions,
        key=lambda x: x["priority_score"],
        reverse=True
    )

    return sorted_places


# Run scoring
scored = calculate_scores(attractions)

ranked = sort_attractions(scored)

print("Top Attractions:\n")

for place in ranked[:10]:
    print(place["name"], "Score:", place["priority_score"])

Top Attractions:

Trimbakeshwar Temple Score: 44.0
Ramkund Score: 40.0
Kalaram Temple Score: 40.0
Harihar Fort Score: 36.0
Muktidham Temple Score: 35.0
Someshwar Waterfall Score: 34.0
Brahmagiri Hills Score: 32.0
Anjaneri Hills Score: 32.0
Sita Gumpha (Sita's Cave) Score: 30.5
Navshya Ganpati Temple Score: 30.25

In [14]:
# Region Clustering Engine

def cluster_by_region(attractions):

    region_clusters = {}

    for place in attractions:

        region = place.get("route_cluster", "Unknown")

        if region not in region_clusters:
            region_clusters[region] = []

        region_clusters[region].append(place)

    return region_clusters


# Run clustering
clusters = cluster_by_region(ranked)


print("Attractions grouped by region:\n")

for region, places in clusters.items():

    print("Region:", region)

    for p in places[:3]:
        print(" -", p["name"])

    print()

Attractions grouped by region:

Region: Trimbakeshwar Route
 - Trimbakeshwar Temple
 - Brahmagiri Hills
 - Anjaneri Hills

Region: Panchavati Area
 - Ramkund
 - Kalaram Temple
 - Sita Gumpha (Sita's Cave)

Region: Adventure Trekking Route
 - Harihar Fort
 - Dugarwadi Waterfall
 - Darna Dam

Region: City Center Attractions
 - Muktidham Temple
 - Nashik Art Gallery (Kala Niketan)
 - Pandavleni Caves

Region: Gangapur Route
 - Someshwar Waterfall
 - Gangapur Dam
 - Nandur Madhmeshwar Bird Sanctuary

In [15]:
# Region Priority Engine

def calculate_region_priority(region_clusters):

    region_priority_list = []

    for region, places in region_clusters.items():

        total_score = 0
        total_fatigue = 0
        total_time = 0

        for place in places:

            total_score += place.get("priority_score", 0)

            fatigue = place.get("fatigue_level", "medium")

            if fatigue == "low":
                fatigue_value = 1
            elif fatigue == "medium":
                fatigue_value = 2
            else:
                fatigue_value = 3

            total_fatigue += fatigue_value
            total_time += place.get("avg_visit_time_hours", 1)

        count = len(places)

        avg_score = total_score / count
        avg_fatigue = total_fatigue / count
        avg_time = total_time / count

        region_score = avg_score - avg_fatigue - avg_time

        region_priority_list.append({
            "region": region,
            "region_score": region_score,
            "places": places
        })

    sorted_regions = sorted(
        region_priority_list,
        key=lambda x: x["region_score"],
        reverse=True
    )

    return sorted_regions


region_priority = calculate_region_priority(clusters)

In [16]:
# Calculate AI score for each attraction

def calculate_attraction_score(place):

    experience = place.get("experience_score", 5)
    fatigue = place.get("fatigue_cost", 2)
    visit_time = place.get("avg_visit_time_hours", 1)

    score = experience - (fatigue * 0.5) - (visit_time * 0.3)

    return round(score, 2)


for place in attractions:
    place["ai_score"] = calculate_attraction_score(place)

In [19]:
from collections import defaultdict

# Group attractions by region

regions = defaultdict(list)

for place in attractions:

    region = place.get("route_cluster", "Unknown")

    regions[region].append(place)


# Sort attractions inside each region by AI score

for region in regions:

    regions[region] = sorted(
        regions[region],
        key=lambda x: x["ai_score"],
        reverse=True
    )

In [20]:
for region in regions:

    print("\nRegion:", region)

    for place in regions[region][:3]:

        print(" -", place["name"], "| Score:", place["ai_score"])

Region: Trimbakeshwar Route
 - Trimbakeshwar Temple | Score: 7.9
 - Brahmagiri Hills | Score: 2.3
 - Anjaneri Hills | Score: 2.3

Region: Panchavati Area
 - Kalaram Temple | Score: 8.2
 - Ramkund | Score: 7.7
 - Navshya Ganpati Temple | Score: 6.28

Region: City Center Attractions
 - Muktidham Temple | Score: 7.2
 - Gargoti Mineral Museum | Score: 6.05
 - Nashik Coin Museum | Score: 5.2

Region: Gangapur Route
 - Sula Vineyards | Score: 7.1
 - Someshwar Waterfall | Score: 5.4
 - York Winery (Nashik Wine Park) | Score: 5.4

Region: Adventure Trekking Route
 - Darna Dam | Score: 2.9
 - Dugarwadi Waterfall | Score: 2.75
 - Harihar Fort | Score: 2.5

In [23]:
days = int(input("Enter number of travel days: "))

Enter number of travel days: 6

In [24]:
def generate_itinerary(regions, days):

    hours_per_day = 8

    itinerary = {}

    region_list = list(regions.keys())

    region_index = 0

    for day in range(1, days + 1):

        remaining_hours = hours_per_day

        itinerary[f"Day {day}"] = []

        while remaining_hours > 0 and region_index < len(region_list):

            current_region = region_list[region_index]

            if len(regions[current_region]) == 0:
                region_index += 1
                continue

            place = regions[current_region][0]

            visit_time = place.get("avg_visit_time_hours", 1)

            if visit_time <= remaining_hours:

                itinerary[f"Day {day}"].append(place)

                remaining_hours -= visit_time

                regions[current_region].pop(0)

            else:
                break

    return itinerary

In [25]:
travel_plan = generate_itinerary(regions, days)

for day in travel_plan:

    print("\n", day)

    total_hours = 0

    for place in sorted(travel_plan[day], key=lambda x: x.get("fatigue_cost",1), reverse=True):

        visit_time = place.get("avg_visit_time_hours",1)

        if total_hours < 3:
            time_slot = "Morning"
        elif total_hours < 6:
            time_slot = "Afternoon"
        else:
            time_slot = "Evening"

        if visit_time <= 0.5:
            print(f"{time_slot} → {place['name']} (Quick Visit) | Region: {place['route_cluster']}")
        else:
            print(f"{time_slot} → {place['name']} | Region: {place['route_cluster']}")

        total_hours += visit_time

 Day 1
Morning → Brahmagiri Hills | Region: Trimbakeshwar Route
Afternoon → Trimbakeshwar Temple | Region: Trimbakeshwar Route

 Day 2
Morning → Anjaneri Hills | Region: Trimbakeshwar Route
Afternoon → Ramkund | Region: Panchavati Area
Afternoon → Sita Gumpha (Sita's Cave) (Quick Visit) | Region: Panchavati Area
Afternoon → Kalaram Temple | Region: Panchavati Area
Evening → Navshya Ganpati Temple | Region: Panchavati Area

 Day 3
Morning → Pandavleni Caves | Region: City Center Attractions
Morning → Muktidham Temple | Region: City Center Attractions
Afternoon → Gargoti Mineral Museum | Region: City Center Attractions
Afternoon → Nashik Coin Museum | Region: City Center Attractions
Afternoon → Nashik Art Gallery (Kala Niketan) | Region: City Center Attractions

 Day 4
Morning → Someshwar Waterfall | Region: Gangapur Route
Morning → Sula Vineyards | Region: Gangapur Route
Afternoon → York Winery (Nashik Wine Park) | Region: Gangapur Route

 Day 5
Morning → Nandur Madhmeshwar Bird Sanctuary | Region: Gangapur Route
Afternoon → Darna Dam | Region: Adventure Trekking Route
Afternoon → Gangapur Dam | Region: Gangapur Route

 Day 6
Morning → Harihar Fort | Region: Adventure Trekking Route
Afternoon → Dugarwadi Waterfall | Region: Adventure Trekking Route

In [26]:



budget = int(input("Enter tota trip budget : "))
people = int(input("Enter number of travelers : "))

Enter tota trip budget : 15000
Enter number of travelers : 5

In [27]:
print("Choose travel style:")
print("1 - Budget Traveler")
print("2 - Balanced Traveler")
print("3 - Luxury Traveler")
print("4 - Food Lover")

style = int(input("Enter option: "))

Choose travel style:
1 - Budget Traveler
2 - Balanced Traveler
3 - Luxury Traveler
4 - Food Lover
Enter option: 1

In [28]:
if style == 1:  # Budget Traveler
    hotel_budget = int(budget * 0.4)
    food_budget = int(budget * 0.25)
    transport_budget = int(budget * 0.35)

elif style == 2:  # Balanced Traveler
    hotel_budget = int(budget * 0.5)
    food_budget = int(budget * 0.25)
    transport_budget = int(budget * 0.25)

elif style == 3:  # Luxury Traveler
    hotel_budget = int(budget * 0.7)
    food_budget = int(budget * 0.2)
    transport_budget = int(budget * 0.1)

elif style == 4:  # Food Lover
    hotel_budget = int(budget * 0.4)
    food_budget = int(budget * 0.4)
    transport_budget = int(budget * 0.2)

else:
    print("Invalid choice, using Balanced Traveler")
    hotel_budget = int(budget * 0.5)
    food_budget = int(budget * 0.25)
    transport_budget = int(budget * 0.25)

In [29]:
print("\nBudget Distribution:")
print("Hotel Budget:", hotel_budget)
print("Food Budget:", food_budget)
print("Transport Budget:", transport_budget)

Budget Distribution:
Hotel Budget: 6000
Food Budget: 3750
Transport Budget: 5250

In [30]:
import json

with open("nashik_hotels_final.json", "r") as f:
    hotels = json.load(f)

print("Total Hotels:", len(hotels))
print(hotels[0])

Total Hotels: 20
{'id': 'ram_krishna_dharamshala', 'hotel_name': 'Ram Krishna Dharamshala', 'hotel_category': 'dharamshala', 'area': 'Panchavati', 'location_city': 'Nashik', 'distance_from_cbs_km': 3.5, 'distance_from_panchavati_km': 0.1, 'distance_from_trimbakeshwar_km': 28.0, 'distance_from_sula_km': 14.5, 'avg_price_per_night': 300, 'price_range': '₹200–₹400', 'cost_per_person_estimate': 150, 'room_types': ['dormitory', 'double'], 'max_guests_per_room': 6, 'recommended_group_size': [1, 2, 4, 6], 'comfort_score': 4, 'cleanliness_score': 6, 'service_score': 5, 'experience_value': 8, 'wifi': False, 'ac': False, 'parking': False, 'restaurant_available': False, 'breakfast_included': False, 'room_service': False, 'swimming_pool': False, 'booking_method': 'Walk-in / Phone', 'booking_link': None, 'advance_booking_required': False, 'checkin_time': '08:00', 'checkout_time': '10:00', 'budget_category': 'budget', 'recommended_for': ['solo', 'budget', 'pilgrim'], 'tourist_popularity': 'High', 'peak_season_price_multiplier': 2.0, 'nearby_attractions': ['ramkund', 'kalaram_temple', 'navshya_ganpati', 'sita_gumpha'], 'route_cluster': 'Panchavati Area', 'distance_to_bus_stand_km': 3.5, 'distance_to_railway_station_km': 11.0, 'transport_availability': ['auto', 'bus', 'uber'], 'family_friendly': True, 'wheelchair_accessible': False, 'safety_score': 7, 'meal_plan_available': 'EP', 'cancellation_policy': 'Free', 'minimum_stay_nights': 1, 'is_pilgrimage_friendly': True, 'noise_level': 'High', 'stars_rating': None, 'has_early_checkin': True, 'has_late_checkout': False, 'description': "Ram Krishna Dharamshala is a simple pilgrims' rest house located just steps from Ramkund in Panchavati. Very basic dormitory and double rooms at extremely affordable rates. Ideal for devotees and budget pilgrims visiting Kalaram Temple and Ramkund.", 'image_url': 'https://www.google.com/search?tbm=isch&q=Dharamshala%20pilgrim%20rest%20house%20India', 'video_url': 'https://www.youtube.com/results?search_query=Panchavati+Nashik+dharamshala+stay', 'hotel_icon_tag': 'dharamshala', 'visitor_rating': 4.1, 'alternative_hotel_id': 'shri_sai_dharamshala', 'is_seasonal': False, 'travel_time_from_cbs_minutes': 15, 'highlight': "Pilgrims' Rest Steps Away from Ramkund", 'total_capacity': 40, 'accepts_large_groups': True, 'distance_from_gangapur_km': 14.0, 'is_central_location': False, 'typically_full_during': ['Shravan', 'Kumbh Mela', 'Ram Navami', 'Diwali'], 'value_score': 26.67, 'seasonal_rating_change': 'Negative', 'includes_tour_package': False, 'pet_friendly': False}

In [31]:
from collections import Counter

def find_main_region(travel_plan):

    regions = []

    for day in travel_plan:
        for place in travel_plan[day]:
            regions.append(place["route_cluster"])

    region_count = Counter(regions)

    main_region = region_count.most_common(1)[0][0]

    return main_region

In [32]:
import math

def calculate_hotel_score(hotel, hotel_budget, days, people, main_region):

    # basic hotel information
    price = hotel["avg_price_per_night"]
    rating = hotel["visitor_rating"]

    comfort = hotel.get("comfort_score", 0)
    cleanliness = hotel.get("cleanliness_score", 0)
    service = hotel.get("service_score", 0)

    region = hotel["route_cluster"]

    # room capacity logic
    room_capacity = hotel.get("max_guests_per_room", 2)

    # number of rooms needed
    rooms_needed = math.ceil(people / room_capacity)

    # total hotel cost
    total_price = rooms_needed * price * days

    # reject hotel if exceeds budget
    if total_price > hotel_budget:
        return -1

    # price efficiency score
    price_efficiency = (hotel_budget - total_price) / hotel_budget

    # region preference
    if region == main_region:
        region_score = 2
    else:
        region_score = 0

    # final AI score
    score = (
        rating * 2 +
        comfort +
        cleanliness +
        service +
        price_efficiency * 5 +
        region_score
    )

    return score

In [33]:
def recommend_hotels(hotels, hotel_budget, days, travel_plan, people):

    main_region = find_main_region(travel_plan)

    scored_hotels = []

    for hotel in hotels:

        score = calculate_hotel_score(
            hotel,
            hotel_budget,
            days,
            people,
            main_region
        )

        if score > 0:
            hotel["ai_score"] = score
            scored_hotels.append(hotel)

    scored_hotels = sorted(
        scored_hotels,
        key=lambda x: x["ai_score"],
        reverse=True
    )

    return scored_hotels[:3]

In [34]:
recommended_hotels = recommend_hotels(
    hotels,
    hotel_budget,
    days,
    travel_plan,
    people


)

print("\nRecommended Hotels:\n")

for i, hotel in enumerate(recommended_hotels, 1):
    print(f"{i}. {hotel['hotel_name']}")
    print("Price per night:", hotel["avg_price_per_night"])
    print("Rating:", hotel["visitor_rating"])
    print("Region:", hotel["route_cluster"])
    print("AI Score:", round(hotel["ai_score"], 2))
    print()

Recommended Hotels:

1. Nashik Backpackers Hostel
Price per night: 450
Rating: 4.3
Region: Nashik Road Route
AI Score: 31.35

2. Ram Krishna Dharamshala
Price per night: 300
Rating: 4.1
Region: Panchavati Area
AI Score: 26.7

3. Shri Sai Dharamshala
Price per night: 250
Rating: 4.0
Region: Trimbakeshwar Route
AI Score: 24.75

In [35]:
import json

with open("nashik_transport_final.json", "r") as f:
    transport_options = json.load(f)

print("Total Transport Options:", len(transport_options))
print(transport_options[0])

Total Transport Options: 34
{'id': 'pune_nashik_msrtc_shivshahi', 'transport_mode': 'MSRTC Shivshahi Bus', 'transport_category': 'intercity_public', 'source_location': 'Pune (Swargate / Shivajinagar)', 'destination_location': 'Nashik CBS', 'distance_km': 210, 'passes_through': ['Sangamner', 'Sinnar'], 'base_travel_time_minutes': 270, 'traffic_sensitivity': 'medium', 'peak_time_multiplier': 1.3, 'avg_cost_per_person': 280, 'cost_type': 'per_person', 'fuel_cost_estimate': None, 'toll_cost': None, 'max_passengers': 52, 'recommended_group_size': [1, 2, 4, 6], 'comfort_score': 7, 'reliability_score': 7, 'crowd_level': 'Medium', 'departure_frequency_minutes': 60, 'service_start_time': '05:30', 'service_end_time': '23:00', 'booking_method': 'Online / Direct Boarding', 'booking_instructions': 'Book via MSRTC official website or purchase ticket at Swargate/Shivajinagar bus stand. Shivshahi is a semi-luxury bus with push-back seats.', 'booking_link': 'https://msrtcreis.in', 'is_ac': False, 'is_scenic_route': False, 'travel_fatigue_score': 5, 'route_popularity': 'High', 'luggage_allowed': True, 'real_time_tracking': False, 'tourist_recommended': True, 'description': 'MSRTC Shivshahi is the most commonly used and affordable bus service from Pune to Nashik. Semi-luxury seating with push-back seats, runs frequently from Swargate and Shivajinagar bus stands.', 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/MSRTC_Shivshahi_bus.jpg/800px-MSRTC_Shivshahi_bus.jpg', 'is_wheelchair_accessible': True, 'child_friendly': True, 'return_trip_available': True, 'supports_multi_stop': False, 'weather_suitability': 'Any', 'cost_per_km': 1.3, 'is_seasonal': False, 'alternative_transport_id': 'pune_nashik_msrtc_shivneri', 'video_url': 'https://www.youtube.com/results?search_query=MSRTC+Shivshahi+Pune+Nashik', 'transport_icon_tag': 'bus', 'avg_cost_per_vehicle': None, 'route_cluster': 'Pune–Nashik Intercity', 'scenic_score': 2, 'recommended_for': ['solo', 'couple', 'budget', 'group']}

In [36]:
 #INPUT CELL (only traveler type required)

traveler_type = input("Enter traveller type (luxury/budget/balanced): ").lower()


print("\nSystem Values Used:\n")

print("Total Travellers:", people)
print("Transport Budget per Person:", transport_budget)

Enter traveller type (luxury/budget/balanced): luxury

System Values Used:

Total Travellers: 5
Transport Budget per Person: 5250

In [ ]:
 #These values should already exist from your planner

In [37]:
def calculate_transport_score(transport, transport_budget, people, traveler_type):

    cost_type = transport.get("cost_type")
    avg_cost = transport.get("avg_cost_per_person")
    fuel_cost = transport.get("fuel_cost_estimate")
    toll_cost = transport.get("toll_cost")

    # ---------- COST CALCULATION ----------
    if cost_type == "per_person":
        cost_per_person = avg_cost if avg_cost else 9999

    elif cost_type == "per_vehicle":
        vehicle_cost = (fuel_cost or 0) + (toll_cost or 0)
        cost_per_person = vehicle_cost / people if people > 0 else vehicle_cost

    else:
        cost_per_person = 9999

    # ---------- BASIC FEATURES ----------
    comfort = transport.get("comfort_score", 5)
    reliability = transport.get("reliability_score", 5)
    fatigue = transport.get("travel_fatigue_score", 5)

    # ---------- PRICE EFFICIENCY ----------
    if transport_budget > 0:
        price_score = (transport_budget - cost_per_person) / transport_budget
    else:
        price_score = 0

    # ---------- TRAVELLER PREFERENCE ----------
    traveler_bonus = 0

    if traveler_type == "luxury":
        traveler_bonus = comfort * 0.6

    elif traveler_type == "budget":
        traveler_bonus = price_score * 5

    elif traveler_type == "balanced":
        traveler_bonus = (comfort + reliability) / 2

    # ---------- GROUP ADVANTAGE ----------
    group_bonus = 0
    if people >= 4 and cost_type == "per_vehicle":
        group_bonus = 2

    # ---------- FINAL AI SCORE ----------
    score = (
        price_score * 5 +
        comfort * 1.5 +
        reliability +
        traveler_bonus +
        group_bonus -
        fatigue
    )

    return score

In [38]:
def recommend_transport_by_region(transport_options, transport_budget, people, traveler_type):

    best_transport = None
    best_score = -999

    for transport in transport_options:

        destination = transport.get("destination_location","").lower()

        # Only consider transport going to Nashik
        if "nashik" not in destination:
            continue

        score = calculate_transport_score(
            transport,
            transport_budget,
            people,
            traveler_type
        )

        if score > best_score:
            best_score = score
            best_transport = transport

    if best_transport:
        best_transport["ai_score"] = best_score

    return best_transport

In [39]:
best_transport = recommend_transport_by_region(
    transport_options,
    transport_budget,
    people,
    traveler_type
)

In [40]:
print("\nRecommended Transport:\n")

transport = best_transport

cost_type = transport.get("cost_type")

if cost_type == "per_person":
    cost_per_person = transport.get("avg_cost_per_person",0)

elif cost_type == "per_vehicle":
    vehicle_cost = (transport.get("fuel_cost_estimate") or 0) + (transport.get("toll_cost") or 0)
    cost_per_person = vehicle_cost / people

else:
    cost_per_person = 0

travel_time = transport.get("base_travel_time_minutes","Unknown")

total_cost = cost_per_person * people

print("Transport Mode:", transport.get("transport_mode"))
print("Source:", transport.get("source_location"))
print("Destination:", transport.get("destination_location"))

print("Cost per Person: ₹", round(cost_per_person,2))
print("Total Cost:", round(total_cost,2))

print("Travel Time (minutes):", travel_time)
print("AI Score:", round(transport.get("ai_score",0),2))

Recommended Transport:

Transport Mode: Outstation Cab (Ola/Local Operator)
Source: Mumbai (Any Location)
Destination: Nashik (Any Location)
Cost per Person: ₹ 280.0
Total Cost: 1400.0
Travel Time (minutes): 210
AI Score: 32.63

In [41]:
len(transport_options)

34

In [42]:
print(travel_plan)

{'Day 1': [{'id': 'trimbakeshwar_temple', 'name': 'Trimbakeshwar Temple', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 200, 'avg_visit_time_hours': 2.0, 'experience_score': 10, 'location_area': 'Trimbak', 'distance_from_nashik_city_km': 28, 'travel_time_from_cbs_minutes': 55, 'best_time_to_visit': 'Morning', 'crowd_level': 'High', 'route_cluster': 'Trimbakeshwar Route', 'route_order': 3, 'accessibility_score': 5, 'food_available_nearby': True, 'transport_modes': ['bus', 'cab', 'private'], 'fatigue_cost': 3, 'indoor_outdoor': 'Both', 'weather_sensitivity': False, 'traffic_sensitivity': 'High', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 400, 'opening_hours': '05:30–21:00', 'nearby_attractions': ['brahmagiri_hills', 'anjaneri_hills'], 'parking_available': True, 'photography_allowed': False, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '06:00', 'description': 'One of the twelve Jyotirlingas of Lord Shiva, Trimbakeshwar Temple is a sacred pilgrimage site nestled at the foot of Brahmagiri Hills. The temple is renowned for its unique three-faced Shivalinga representing Brahma, Vishnu, and Shiva.', 'visitor_rating': 4.7, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Trimbakeshwar_temple.jpg/640px-Trimbakeshwar_temple.jpg', 'priority_score': 44.0, 'ai_score': 7.9}, {'id': 'brahmagiri_hills', 'name': 'Brahmagiri Hills', 'category': 'Adventure', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 4.0, 'experience_score': 8, 'location_area': 'Trimbak', 'distance_from_nashik_city_km': 30, 'travel_time_from_cbs_minutes': 60, 'best_time_to_visit': 'Morning', 'crowd_level': 'Low', 'route_cluster': 'Trimbakeshwar Route', 'route_order': 2, 'accessibility_score': 3, 'food_available_nearby': False, 'transport_modes': ['cab', 'private'], 'fatigue_cost': 9, 'indoor_outdoor': 'Outdoor', 'weather_sensitivity': True, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'group'], 'avg_cost_per_person': 400, 'opening_hours': '05:00–17:00', 'nearby_attractions': ['trimbakeshwar_temple', 'anjaneri_hills'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Winter', 'family_friendly': False, 'typical_visit_start_time': '06:00', 'description': 'Brahmagiri Hills is a sacred mountain range near Trimbakeshwar from which the Godavari River originates. The trek to the summit takes visitors through dense forests and offers a spiritual experience along with stunning natural scenery.', 'visitor_rating': 4.4, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Brahmagiri_Hills.jpg/640px-Brahmagiri_Hills.jpg', 'priority_score': 32.0, 'ai_score': 2.3}], 'Day 2': [{'id': 'anjaneri_hills', 'name': 'Anjaneri Hills', 'category': 'Adventure', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 4.0, 'experience_score': 8, 'location_area': 'Trimbak', 'distance_from_nashik_city_km': 25, 'travel_time_from_cbs_minutes': 50, 'best_time_to_visit': 'Morning', 'crowd_level': 'Low', 'route_cluster': 'Trimbakeshwar Route', 'route_order': 1, 'accessibility_score': 3, 'food_available_nearby': False, 'transport_modes': ['cab', 'private'], 'fatigue_cost': 9, 'indoor_outdoor': 'Outdoor', 'weather_sensitivity': True, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'group'], 'avg_cost_per_person': 350, 'opening_hours': '05:00–17:00', 'nearby_attractions': ['brahmagiri_hills', 'trimbakeshwar_temple'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Winter', 'family_friendly': False, 'typical_visit_start_time': '05:30', 'description': 'Anjaneri Hills is the legendary birthplace of Lord Hanuman, making it a site of both spiritual and trekking significance. The trek offers a moderate to challenging climb through rocky terrain with rewarding views from the top.', 'visitor_rating': 4.3, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Anjaneri_mountain.jpg/640px-Anjaneri_mountain.jpg', 'priority_score': 32.0, 'ai_score': 2.3}, {'id': 'kalaram_temple', 'name': 'Kalaram Temple', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 1.0, 'experience_score': 9, 'location_area': 'Panchavati', 'distance_from_nashik_city_km': 3, 'travel_time_from_cbs_minutes': 10, 'best_time_to_visit': 'Morning', 'crowd_level': 'High', 'route_cluster': 'Panchavati Area', 'route_order': 2, 'accessibility_score': 8, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private', 'walk'], 'fatigue_cost': 1, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'High', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 100, 'opening_hours': '05:30–21:30', 'nearby_attractions': ['ramkund', 'navshya_ganpati', 'sita_gumpha'], 'parking_available': False, 'photography_allowed': False, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '06:30', 'description': 'Kalaram Temple is one of the most important Hindu temples in Nashik, dedicated to Lord Ram. The temple is built entirely from black stone and stands as a magnificent example of Hemadpanthi architecture.', 'visitor_rating': 4.6, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Kalaram_temple_nashik.jpg/640px-Kalaram_temple_nashik.jpg', 'priority_score': 40.0, 'ai_score': 8.2}, {'id': 'ramkund', 'name': 'Ramkund', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 1.0, 'experience_score': 9, 'location_area': 'Panchavati', 'distance_from_nashik_city_km': 3, 'travel_time_from_cbs_minutes': 10, 'best_time_to_visit': 'Morning', 'crowd_level': 'High', 'route_cluster': 'Panchavati Area', 'route_order': 1, 'accessibility_score': 7, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private', 'walk'], 'fatigue_cost': 2, 'indoor_outdoor': 'Outdoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'High', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 150, 'opening_hours': '05:00–21:00', 'nearby_attractions': ['kalaram_temple', 'navshya_ganpati', 'sita_gumpha'], 'parking_available': False, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '06:00', 'description': 'Ramkund is a sacred bathing tank on the banks of the Godavari River in Panchavati, believed to be the spot where Lord Ram bathed during his exile. The kund holds deep religious significance and is surrounded by numerous small temples.', 'visitor_rating': 4.5, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/1/17/Ram_Kund_Nashik.jpg', 'priority_score': 40.0, 'ai_score': 7.7}, {'id': 'navshya_ganpati', 'name': 'Navshya Ganpati Temple', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 0.75, 'experience_score': 7, 'location_area': 'Panchavati', 'distance_from_nashik_city_km': 3, 'travel_time_from_cbs_minutes': 12, 'best_time_to_visit': 'Morning', 'crowd_level': 'Medium', 'route_cluster': 'Panchavati Area', 'route_order': 3, 'accessibility_score': 9, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private', 'walk'], 'fatigue_cost': 1, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'Medium', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 80, 'opening_hours': '06:00–21:00', 'nearby_attractions': ['kalaram_temple', 'ramkund', 'sita_gumpha'], 'parking_available': False, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '07:00', 'description': 'Navshya Ganpati is a beloved Ganesh temple in the Panchavati area of Nashik, known for the distinct black stone idol of Lord Ganesha. It is a peaceful stop for devotees exploring the Panchavati pilgrimage circuit.', 'visitor_rating': 4.3, 'image_url': 'https://www.google.com/search?tbm=isch&q=Navshya%20Ganpati%20Temple%20Nashik', 'priority_score': 30.25, 'ai_score': 6.28}, {'id': 'sita_gumpha', 'name': "Sita Gumpha (Sita's Cave)", 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 0.5, 'experience_score': 7, 'location_area': 'Panchavati', 'distance_from_nashik_city_km': 3.5, 'travel_time_from_cbs_minutes': 12, 'best_time_to_visit': 'Morning', 'crowd_level': 'Medium', 'route_cluster': 'Panchavati Area', 'route_order': 4, 'accessibility_score': 5, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'walk'], 'fatigue_cost': 2, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 80, 'opening_hours': '06:00–18:00', 'nearby_attractions': ['kalaram_temple', 'ramkund', 'navshya_ganpati'], 'parking_available': False, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '07:30', 'description': 'Sita Gumpha is a small cave shrine in Panchavati believed to be the place where Sita resided during her exile with Lord Ram and Laxman. The cave has a narrow entrance and holds a small idol of Goddess Sita inside.', 'visitor_rating': 4.1, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Sita_Gupha%2C_Nashik.jpg/640px-Sita_Gupha%2C_Nashik.jpg', 'priority_score': 30.5, 'ai_score': 5.85}], 'Day 3': [{'id': 'muktidham_temple', 'name': 'Muktidham Temple', 'category': 'Spiritual', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 1.0, 'experience_score': 8, 'location_area': 'College Road', 'distance_from_nashik_city_km': 5, 'travel_time_from_cbs_minutes': 15, 'best_time_to_visit': 'Morning', 'crowd_level': 'Medium', 'route_cluster': 'City Center Attractions', 'route_order': 1, 'accessibility_score': 9, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private'], 'fatigue_cost': 1, 'indoor_outdoor': 'Both', 'weather_sensitivity': False, 'traffic_sensitivity': 'Medium', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 100, 'opening_hours': '07:00–21:00', 'nearby_attractions': ['coin_museum', 'pandavleni_caves'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '08:00', 'description': 'Muktidham Temple is a beautifully crafted white marble temple complex that houses replicas of all twelve Jyotirlingas of India. The walls are engraved with verses from the Bhagavad Gita, making it a unique spiritual and architectural attraction.', 'visitor_rating': 4.4, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Muktidham_temple_nashik.jpg/640px-Muktidham_temple_nashik.jpg', 'priority_score': 35.0, 'ai_score': 7.2}, {'id': 'gargoti_mineral_museum', 'name': 'Gargoti Mineral Museum', 'category': 'Cultural', 'entry_fee': 150, 'vip_fee': 0, 'avg_visit_time_hours': 1.5, 'experience_score': 7, 'location_area': 'Sinnar, Nashik', 'distance_from_nashik_city_km': 32, 'travel_time_from_cbs_minutes': 55, 'best_time_to_visit': 'Any', 'crowd_level': 'Low', 'route_cluster': 'City Center Attractions', 'route_order': 5, 'accessibility_score': 9, 'food_available_nearby': False, 'transport_modes': ['cab', 'private'], 'fatigue_cost': 1, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 250, 'opening_hours': '09:00–17:00', 'nearby_attractions': ['pandavleni_caves', 'coin_museum'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '10:00', 'description': "Gargoti Mineral Museum in Sinnar houses one of the world's finest collections of minerals, crystals, and gemstones from India and abroad. The museum is a fascinating educational experience for geology enthusiasts and curious visitors of all ages.", 'visitor_rating': 4.4, 'image_url': 'https://www.google.com/search?tbm=isch&q=Gargoti%20Museum%20Nashik%20minerals', 'priority_score': -120.5, 'ai_score': 6.05}, {'id': 'coin_museum', 'name': 'Nashik Coin Museum', 'category': 'Cultural', 'entry_fee': 20, 'vip_fee': 0, 'avg_visit_time_hours': 1.0, 'experience_score': 6, 'location_area': 'Canada Corner', 'distance_from_nashik_city_km': 4, 'travel_time_from_cbs_minutes': 12, 'best_time_to_visit': 'Any', 'crowd_level': 'Low', 'route_cluster': 'City Center Attractions', 'route_order': 3, 'accessibility_score': 9, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private'], 'fatigue_cost': 1, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 100, 'opening_hours': '10:00–17:00', 'nearby_attractions': ['muktidham_temple', 'pandavleni_caves'], 'parking_available': True, 'photography_allowed': False, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '10:30', 'description': "The Indian Institute of Research in Numismatic Studies houses one of India's finest coin museums, displaying thousands of coins from ancient to modern times. It is an educational treasure for history enthusiasts and researchers.", 'visitor_rating': 4.0, 'image_url': 'https://www.google.com/search?tbm=isch&q=IIRNS%20Nashik%20Coin%20Museum', 'priority_score': 5.0, 'ai_score': 5.2}, {'id': 'pandavleni_caves', 'name': 'Pandavleni Caves', 'category': 'Heritage', 'entry_fee': 25, 'vip_fee': 0, 'avg_visit_time_hours': 2.0, 'experience_score': 8, 'location_area': 'Trirashmi Hill', 'distance_from_nashik_city_km': 8, 'travel_time_from_cbs_minutes': 20, 'best_time_to_visit': 'Morning', 'crowd_level': 'Medium', 'route_cluster': 'City Center Attractions', 'route_order': 2, 'accessibility_score': 4, 'food_available_nearby': False, 'transport_modes': ['auto', 'cab', 'private'], 'fatigue_cost': 5, 'indoor_outdoor': 'Both', 'weather_sensitivity': True, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 200, 'opening_hours': '08:00–17:30', 'nearby_attractions': ['muktidham_temple', 'coin_museum'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '09:00', 'description': 'Pandavleni Caves is a group of 24 ancient rock-cut caves dating back to the 1st century BC, carved by Buddhist monks. The caves contain well-preserved sculptures, inscriptions, and water cisterns carved into the Trirashmi Hill.', 'visitor_rating': 4.4, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Pandav_Leni_Caves.jpg/640px-Pandav_Leni_Caves.jpg', 'priority_score': 9.0, 'ai_score': 4.9}, {'id': 'nashik_art_gallery', 'name': 'Nashik Art Gallery (Kala Niketan)', 'category': 'Cultural', 'entry_fee': 10, 'vip_fee': 0, 'avg_visit_time_hours': 1.0, 'experience_score': 5, 'location_area': 'Nashik Road', 'distance_from_nashik_city_km': 5, 'travel_time_from_cbs_minutes': 12, 'best_time_to_visit': 'Afternoon', 'crowd_level': 'Low', 'route_cluster': 'City Center Attractions', 'route_order': 4, 'accessibility_score': 9, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'bus', 'private'], 'fatigue_cost': 1, 'indoor_outdoor': 'Indoor', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 80, 'opening_hours': '10:00–17:30', 'nearby_attractions': ['coin_museum', 'muktidham_temple'], 'parking_available': True, 'photography_allowed': False, 'seasonal_availability': 'Year-round', 'family_friendly': True, 'typical_visit_start_time': '11:00', 'description': "Nashik Art Gallery, also known as Kala Niketan, showcases works by local and regional artists, offering a window into Nashik's vibrant contemporary and traditional art scene. It is a calm cultural stop for art enthusiasts.", 'visitor_rating': 3.8, 'image_url': 'https://www.google.com/search?tbm=isch&q=Nashik%20Art%20Gallery%20Kala%20Niketan', 'priority_score': 10.0, 'ai_score': 4.2}], 'Day 4': [{'id': 'sula_vineyards', 'name': 'Sula Vineyards', 'category': 'Leisure', 'entry_fee': 200, 'vip_fee': 0, 'avg_visit_time_hours': 3.0, 'experience_score': 9, 'location_area': 'Gaulane Village, Gangapur Road', 'distance_from_nashik_city_km': 14, 'travel_time_from_cbs_minutes': 30, 'best_time_to_visit': 'Afternoon', 'crowd_level': 'Medium', 'route_cluster': 'Gangapur Route', 'route_order': 3, 'accessibility_score': 8, 'food_available_nearby': True, 'transport_modes': ['cab', 'private'], 'fatigue_cost': 2, 'indoor_outdoor': 'Both', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'group'], 'avg_cost_per_person': 800, 'opening_hours': '11:00–22:00', 'nearby_attractions': ['gangapur_dam', 'someshwar_waterfall'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': False, 'typical_visit_start_time': '14:00', 'description': "Sula Vineyards is India's most celebrated winery, set amidst lush green vineyards on the outskirts of Nashik. Visitors can enjoy guided wine tours, tastings, and a rooftop restaurant overlooking the Gangapur reservoir.", 'visitor_rating': 4.5, 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Sula_Vineyards.jpg/640px-Sula_Vineyards.jpg', 'priority_score': -162.0, 'ai_score': 7.1}, {'id': 'someshwar_waterfall', 'name': 'Someshwar Waterfall', 'category': 'Nature', 'entry_fee': 0, 'vip_fee': 0, 'avg_visit_time_hours': 2.0, 'experience_score': 8, 'location_area': 'Someshwar', 'distance_from_nashik_city_km': 12, 'travel_time_from_cbs_minutes': 25, 'best_time_to_visit': 'Morning', 'crowd_level': 'High', 'route_cluster': 'Gangapur Route', 'route_order': 2, 'accessibility_score': 5, 'food_available_nearby': True, 'transport_modes': ['auto', 'cab', 'private'], 'fatigue_cost': 4, 'indoor_outdoor': 'Outdoor', 'weather_sensitivity': True, 'traffic_sensitivity': 'Medium', 'group_suitability': ['solo', 'couple', 'family', 'group'], 'avg_cost_per_person': 200, 'opening_hours': '06:00–18:00', 'nearby_attractions': ['gangapur_dam', 'sula_vineyards'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Monsoon', 'family_friendly': True, 'typical_visit_start_time': '08:00', 'description': 'Someshwar Waterfall is a picturesque cascade flowing through a rocky gorge near the Someshwar village. The waterfall is at its most stunning during and after the monsoon season, attracting nature lovers and photographers.', 'visitor_rating': 4.3, 'image_url': 'https://www.google.com/search?tbm=isch&q=Someshwar%20Waterfall%20Nashik', 'priority_score': 34.0, 'ai_score': 5.4}, {'id': 'nashik_wine_park', 'name': 'York Winery (Nashik Wine Park)', 'category': 'Leisure', 'entry_fee': 150, 'vip_fee': 0, 'avg_visit_time_hours': 2.0, 'experience_score': 7, 'location_area': 'Gangapur Road', 'distance_from_nashik_city_km': 13, 'travel_time_from_cbs_minutes': 28, 'best_time_to_visit': 'Afternoon', 'crowd_level': 'Low', 'route_cluster': 'Gangapur Route', 'route_order': 4, 'accessibility_score': 8, 'food_available_nearby': True, 'transport_modes': ['cab', 'private'], 'fatigue_cost': 2, 'indoor_outdoor': 'Both', 'weather_sensitivity': False, 'traffic_sensitivity': 'Low', 'group_suitability': ['solo', 'couple', 'group'], 'avg_cost_per_person': 700, 'opening_hours': '10:00–19:00', 'nearby_attractions': ['sula_vineyards', 'gangapur_dam'], 'parking_available': True, 'photography_allowed': True, 'seasonal_availability': 'Year-round', 'family_friendly': False, 'typical_visit_start_time': '14:30', 'description': 'York Winery is a boutique vi

In [43]:
print("trave plan type",type(travel_plan))
print("travel plan value:",travel_plan)

trave plan type <class 'dict'>

In [44]:
import json

with open("nashik_intracity_transport_dataset.json", "r", encoding="utf-8", errors="ignore") as file:
    intracity_transport_options = json.load(file)

print("Intracity transport routes loaded:", len(intracity_transport_options))

Intracity transport routes loaded: 9

In [45]:
def calculate_intracity_transport_score(transport, people, traveler_type):

    cost_type = transport.get("cost_type")
    avg_cost = transport.get("avg_cost_per_person")
    fuel_cost = transport.get("fuel_cost_estimate", 0)
    toll_cost = transport.get("toll_cost", 0)

    # cost calculation
    if cost_type == "per_person":
        cost_per_person = avg_cost
        total_cost = avg_cost * people

    elif cost_type == "per_vehicle":
        vehicle_cost = (fuel_cost or 0) + (toll_cost or 0)
        cost_per_person = vehicle_cost / people
        total_cost = vehicle_cost

    else:
        cost_per_person = avg_cost
        total_cost = avg_cost * people

    comfort = transport.get("comfort_score",5)
    reliability = transport.get("reliability_score",5)
    fatigue = transport.get("travel_fatigue_score",5)

    # traveler preference
    traveler_bonus = 0

    if traveler_type == "luxury":
        traveler_bonus = comfort * 0.5

    elif traveler_type == "budget":
        traveler_bonus = max(0,10 - cost_per_person) * 0.3

    elif traveler_type == "balanced":
        traveler_bonus = (comfort + reliability) * 0.2

    # AI score
    score = (
        comfort * 1.5 +
        reliability * 1.5 +
        traveler_bonus -
        fatigue * 0.5
    )

    return score

In [46]:
def recommend_intracity_transport(travel_plan, intracity_transport_options, people, traveler_type):

    print("\nIntracity Transport Recommendations:\n")

    for day in travel_plan:

        places = travel_plan[day]

        for i in range(len(places)-1):

            source = places[i]["name"]
            destination = places[i+1]["name"]

            best_transport = None
            best_score = -999

            for transport in intracity_transport_options:

                if transport["source_location"] in source or transport["destination_location"] in destination:

                    score = calculate_intracity_transport_score(
                        transport,
                        people,
                        traveler_type
                    )

                    if score > best_score:
                        best_score = score
                        best_transport = transport

            if best_transport:

                cost_per_person = best_transport.get("avg_cost_per_person",0)
                travel_time = best_transport.get("base_travel_time_minutes","Unknown")

                print("Route:", source, "→", destination)
                print("Transport Mode:", best_transport["transport_mode"])
                print("Cost per Person: ₹", cost_per_person)
                print("Total Cost:", cost_per_person * people)
                print("Travel Time (minutes):", travel_time)
                print("AI Score:", round(best_score,2))
                print("-"*40)

In [47]:
recommend_intracity_transport(
    travel_plan,
    intracity_transport_options,
    people,
    traveler_type
)

Intracity Transport Recommendations:

Route: Trimbakeshwar Temple → Brahmagiri Hills
Transport Mode: Shared Auto
Cost per Person: ₹ 50
Total Cost: 250
Travel Time (minutes): 15
AI Score: 17.0
----------------------------------------

In [48]:
import json

with open("nashik_food_final_v2.json","r",encoding="utf-8") as file:
    food_options = json.load(file)

print("Food dataset loaded:", len(food_options))

Food dataset loaded: 20

In [49]:
from datetime import datetime

def detect_meal_time():

    hour = datetime.now().hour

    if 6 <= hour < 11:
        return "Breakfast"

    elif 11 <= hour < 16:
        return "Lunch"

    elif 16 <= hour < 19:
        return "Evening Snacks"

    else:
        return "Dinner"

In [50]:
def calculate_food_score(food, attraction_name, people, traveler_type, food_preference):

    score = 0

    # ------------------------------------------------
    # Nearby attraction relevance
    # ------------------------------------------------
    if attraction_name.lower() in [a.lower() for a in food.get("nearby_attractions",[])]:
        score += 10


    # ------------------------------------------------
    # Experience score
    # ------------------------------------------------
    score += food.get("experience_score",0) * 2


    # ------------------------------------------------
    # Visitor rating
    # ------------------------------------------------
    score += food.get("visitor_rating",0) * 2


    # ------------------------------------------------
    # Famous place bonus
    # ------------------------------------------------
    if food.get("visit_priority") == "Must Visit":
        score += 6

    elif food.get("visit_priority") == "Recommended":
        score += 3


    # ------------------------------------------------
    # Waiting time penalty
    # ------------------------------------------------
    waiting = food.get("waiting_time_minutes",0)

    if waiting > 20:
        score -= 3


    # ------------------------------------------------
    # Fatigue recovery
    # ------------------------------------------------
    score += food.get("fatigue_recovery_score",0)


    # ------------------------------------------------
    # Food preference filtering
    # ------------------------------------------------
    if food_preference == "veg":
        if food.get("type") == "Veg":
            score += 5
        else:
            score -= 10


    # ------------------------------------------------
    # Traveler type influence
    # ------------------------------------------------
    cost = food.get("avg_cost_per_person",0)

    if traveler_type == "budget":

        if cost <= 200:
            score += 5
        else:
            score -= 3

    elif traveler_type == "luxury":

        if cost >= 500:
            score += 5

    elif traveler_type == "balanced":

        if 100 <= cost <= 400:
            score += 4


    # ------------------------------------------------
    # Group size compatibility
    # ------------------------------------------------
    if people in food.get("suitable_for_group_size",[]):
        score += 3


    return score

In [51]:
def meal_match(food, meal_time):

    if meal_time == "Breakfast":
        return food.get("serves_breakfast",False)

    elif meal_time == "Lunch":
        return food.get("serves_lunch",False)

    elif meal_time == "Dinner":
        return food.get("serves_dinner",False)

    elif meal_time == "Evening Snacks":
        return food.get("meal_type") == "Evening Snacks"

    return False

In [52]:
def recommend_food(travel_plan, food_options, people, traveler_type, food_preference):

    meal_time = detect_meal_time()

    print("\nMeal Time:", meal_time)
    print("\nFood Recommendations\n")


    for day in travel_plan:

        places = travel_plan[day]

        for place in places:

            attraction = place["id"]

            best_food = None
            best_score = -999


            for food in food_options:

                if not meal_match(food, meal_time):
                    continue


                score = calculate_food_score(
                    food,
                    attraction,
                    people,
                    traveler_type,
                    food_preference
                )


                if score > best_score:
                    best_score = score
                    best_food = food


            if best_food:

                cost_per_person = best_food.get("avg_cost_per_person",0)
                total_cost = cost_per_person * people

                print("Attraction:", place["name"])
                print("Recommended Food Place:", best_food["name"])
                print("Category:", best_food["category"])
                print("Location:", best_food["location_area"])

                print("Cost per Person: ₹", cost_per_person)
                print("Total Cost:", total_cost)

                print("Visitor Rating:", best_food.get("visitor_rating"))
                print("Highlight:", best_food.get("highlight"))

                print("AI Score:", round(best_score,2))
                print("-"*40)

In [53]:
food_preference = "veg"  # veg / non-veg / both

recommend_food(
    travel_plan,
    food_options,
    people,
    traveler_type,
    food_preference
)

Meal Time: Breakfast

Food Recommendations

In [54]:
import json

with open("nashik_food_final_v2.json", "r", encoding="utf-8") as file:
    food_data = json.load(file)

print("Food places loaded:", len(food_data))

Food places loaded: 20

In [55]:
from datetime import datetime, timedelta

# Trip start time
start_time = datetime.strptime("08:00", "%H:%M")

In [56]:
def format_time(t):
    return t.strftime("%I:%M %p")

In [57]:
from datetime import datetime, timedelta

def format_time(t):
    return t.strftime("%I:%M %p")


def generate_timetable(travel_plan, food_data, transport_data, hotel_data, people):

    print("\n==============================")
    print("AI SMART TRAVEL TIMETABLE")
    print("==============================")

    used_food = set()

    for day_index, (day, attractions) in enumerate(travel_plan.items()):

        print("\nDAY", day_index + 1)
        print("-----------------------------")

        current_time = datetime.strptime("08:00", "%H:%M")

        # -------- HOTEL CHECK-IN (only Day 1) --------
        if day_index == 0:
            hotel = hotel_data[0]   # recommended hotel already selected earlier

            print("\n" + format_time(current_time))
            print("Hotel Check-in →", hotel.get("name", hotel.get("hotel_name","Hotel")))
            print("Location:", hotel.get("location_area", hotel.get("location","")))

            hotel_price = hotel.get("price_per_night", hotel.get("avg_cost_per_night", hotel.get("price", 5000)))
            hotel_cost = hotel_price * people
            print("Stay Cost: ₹" + str(hotel_cost))

            print("Check-in & Freshen Up: 60 minutes")

            current_time += timedelta(minutes=60)

        # -------- BREAKFAST --------
        breakfast = None
        for food in food_data:
            if food["serves_breakfast"] and food["name"] not in used_food:
                breakfast = food
                used_food.add(food["name"])
                break

        if breakfast:
            print("\n" + format_time(current_time))
            print("Breakfast –", breakfast["name"])
            print("Famous For:", breakfast.get("highlight",""))

            total_food_cost = breakfast["avg_cost_per_person"] * people
            print("Cost: ₹" + str(total_food_cost))

            print("Meal Time:", breakfast["avg_meal_duration_minutes"], "minutes")

            current_time += timedelta(minutes=breakfast["avg_meal_duration_minutes"])

        lunch_added = False

        for i, place in enumerate(attractions):

            visit_minutes = place.get("avg_visit_time_hours",1) * 60

            print("\n" + format_time(current_time))
            print("Visit", place["name"])

            if "description" in place:
                print("Description:", place["description"][:80])

            print("Visit Duration:", int(visit_minutes), "minutes")

            current_time += timedelta(minutes=visit_minutes)

            # -------- TRANSPORT --------
            if i < len(attractions) - 1:

                next_place = attractions[i+1]

                print("\n" + format_time(current_time))
                print("Travel → Auto Rickshaw")
                print(place["name"], "→", next_place["name"])
                print("Travel Time: 5 minutes")

                transport_cost = 20 * people
                print("Cost: ₹" + str(transport_cost))

                current_time += timedelta(minutes=5)

            # -------- LUNCH --------
            if not lunch_added and current_time.hour >= 13:

                lunch = None
                for food in food_data:
                    if food["serves_lunch"] and food["name"] not in used_food:
                        lunch = food
                        used_food.add(food["name"])
                        break

                if lunch:

                    print("\n" + format_time(current_time))
                    print("Lunch –", lunch["name"])
                    print("Famous Dish:", lunch.get("highlight",""))

                    total_food_cost = lunch["avg_cost_per_person"] * people
                    print("Cost: ₹" + str(total_food_cost))

                    print("Meal Duration:", lunch["avg_meal_duration_minutes"], "minutes")

                    current_time += timedelta(minutes=lunch["avg_meal_duration_minutes"])
                    lunch_added = True

In [58]:
with open("nashik_hotels_final.json","r",encoding="utf-8") as file:
    hotel_data = json.load(file)

In [60]:
generate_timetable(travel_plan, food_data, intracity_transport_options, hotel_data, people)

==============================
AI SMART TRAVEL TIMETABLE
==============================

DAY 1
-----------------------------

08:00 AM
Hotel Check-in → Ram Krishna Dharamshala
Location:
Stay Cost: ₹25000
Check-in & Freshen Up: 60 minutes

KeyError: 'serves_breakfast'

In [61]:
def generate_complete_ai_dashboard(travel_plan, hotel_data, food_data, people, days, budget=10000):

    # -----------------------------
    # 📍 SAFE HELPERS (NO ERROR)
    # -----------------------------
    def safe_get(d, key, default):
        return d[key] if key in d and d[key] is not None else default

    # -----------------------------
    # 📍 ATTRACTIONS (DYNAMIC)
    # -----------------------------
    attraction_names = []
    total_experience = 0
    total_fatigue = 0

    for day in travel_plan:
        for p in travel_plan[day]:
            attraction_names.append(safe_get(p, "name", "Unknown Place"))
            total_experience += safe_get(p, "experience_score", 5)
            total_fatigue += safe_get(p, "fatigue_cost", 2)

    total_places = len(attraction_names)

    # -----------------------------
    # 🏨 SMART HOTEL SELECTION
    # -----------------------------
    per_day_budget = budget / max(days, 1)

    suitable_hotels = [
        h for h in hotel_data
        if safe_get(h, "price_per_night", safe_get(h, "avg_cost_per_night", 800)) <= per_day_budget
    ]

    if suitable_hotels:
        hotel = sorted(suitable_hotels, key=lambda x: safe_get(x, "rating", 4), reverse=True)[0]
    else:
        hotel = hotel_data[0]

    hotel_name = safe_get(hotel, "name", safe_get(hotel, "hotel_name", "Hotel"))
    hotel_location = safe_get(hotel, "location_area", "City Center")

    hotel_price = safe_get(
        hotel,
        "price_per_night",
        safe_get(hotel, "avg_cost_per_night", 800)
    )

    hotel_cost = hotel_price * people * days

    # -----------------------------
    # 🍽 FOOD (DYNAMIC + SAFE)
    # -----------------------------
    selected_food = food_data[:days]

    food_names = [
        safe_get(f, "name", safe_get(f, "food_name", "Food Place"))
        for f in selected_food
    ]

    food_cost = sum(
        safe_get(f, "avg_cost_per_person", 0) * people
        for f in selected_food
    )

    # -----------------------------
    # 📊 AI CALCULATIONS
    # -----------------------------
    avg_experience = total_experience / max(total_places, 1)
    avg_fatigue = total_fatigue / max(total_places, 1)

    total_cost = hotel_cost + food_cost

    # -----------------------------
    # 📈 AI SCORES (DYNAMIC)
    # -----------------------------
    cost_efficiency = max(0, 10 - (total_cost / (budget + 1)) * 10)
    experience_score = min(10, avg_experience * 1.5)
    fatigue_score = max(0, 10 - avg_fatigue * 1.5)

    coverage = "High" if total_places >= 12 else "Medium" if total_places >= 8 else "Low"
    fatigue_label = "Low" if avg_fatigue < 2 else "Medium" if avg_fatigue < 4 else "High"

    # -----------------------------
    # 🤖 AI INSIGHTS (SMART)
    # -----------------------------
    insights = []

    if total_cost <= budget:
        insights.append("💰 Budget is well optimized")
    else:
        insights.append("⚠️ Budget exceeded — optimization needed")

    if experience_score > 8:
        insights.append("⭐ High-quality attractions selected")

    if avg_fatigue > 3:
        insights.append("⚡ Travel may feel tiring")

    if total_places > days * 4:
        insights.append("📍 Too many places per day — may rush trip")

    # -----------------------------
    # 💡 SUGGESTIONS (ACTIONABLE)
    # -----------------------------
    suggestions = []

    if total_cost > budget:
        suggestions.append("💰 Reduce cost by selecting budget hotels")

    if avg_fatigue > 3:
        suggestions.append("⚡ Remove 1–2 places to reduce fatigue")

    if total_places < 8:
        suggestions.append("➕ Add more attractions for better coverage")

    suggestions.append("✨ Add hidden gems for unique experience")

    # -----------------------------
    # 📦 PACKAGE SUMMARY (CLEAN)
    # -----------------------------
    package_summary = {
        "destination": "Nashik",
        "duration": f"{days} Days",
        "group_size": f"{people} People",

        "hotel": {
            "name": hotel_name,
            "location": hotel_location,
            "cost": int(hotel_cost)
        },

        "food": {
            "places": food_names,
            "cost": int(food_cost)
        },

        "attractions": {
            "count": total_places,
            "names": attraction_names[:12]  # UI friendly
        },

        "total_cost": int(total_cost),
        "budget": int(budget)
    }

    # -----------------------------
    # 🎯 FINAL DASHBOARD OUTPUT
    # -----------------------------
    return {
        "package_summary": package_summary,

        "ai_scores": {
            "cost_efficiency": round(cost_efficiency, 1),
            "experience_score": round(experience_score, 1),
            "fatigue_score": round(fatigue_score, 1),
            "coverage": coverage,
            "fatigue_level": fatigue_label
        },

        "insights": insights,
        "suggestions": suggestions
    }

In [62]:
# =========================================
# 🚀 FINAL UI-READY DASHBOARD CALL FUNCTION
# =========================================

def run_ai_dashboard_ui(days, people, budget):

    # -----------------------------
    # 📍 GENERATE PLAN (DYNAMIC)
    # -----------------------------
    plan = generate_itinerary(regions, int(days))

    # -----------------------------
    # 📊 GENERATE DASHBOARD
    # -----------------------------
    dashboard = generate_complete_ai_dashboard(
        travel_plan=plan,
        hotel_data=hotels,
        food_data=food_options,
        people=int(people),
        days=int(days),
        budget=int(budget)
    )

    return dashboard

In [63]:
def smart_budget_adjustment(total_cost, budget,
                            hotel_cost,
                            food_cost,
                            transport_cost,
                            attraction_cost):

    print("\n===== SMART BUDGET CONTROLLER =====")

    min_budget_use = budget * 0.9

    if total_cost <= budget and total_cost >= min_budget_use:

        print("Budget Utilization Perfect ✔")
        return total_cost


    if total_cost > budget:

        exceed = total_cost - budget

        print("⚠ Budget exceeded by ₹", exceed)

        print("\nApplying Priority Adjustment...")

        # Priority 1: Reduce Hotel Cost
        if hotel_cost > 0:

            reduction = min(hotel_cost * 0.3, exceed)

            hotel_cost -= reduction
            exceed -= reduction

            print("Hotel downgraded → saved ₹", int(reduction))


        # Priority 2: Reduce Food Cost
        if exceed > 0 and food_cost > 0:

            reduction = min(food_cost * 0.25, exceed)

            food_cost -= reduction
            exceed -= reduction

            print("Food optimized → saved ₹", int(reduction))


        # Priority 3: Reduce Transport Cost
        if exceed > 0 and transport_cost > 0:

            reduction = min(transport_cost * 0.2, exceed)

            transport_cost -= reduction
            exceed -= reduction

            print("Transport adjusted → saved ₹", int(reduction))


        new_total = hotel_cost + food_cost + transport_cost + attraction_cost

        print("\nAdjusted Package Cost : ₹", int(new_total))

        return new_total


    if total_cost < min_budget_use:

        print("Budget underutilized")

        improvement = min_budget_use - total_cost

        print("Adding better experiences worth ₹", int(improvement))

        return min_budget_use

In [64]:
# Get recommended hotel
hotel = hotel_data[0]

# Smart hotel pricing (based on rating if price not available)
hotel_rating = hotel.get("rating", 4)

if hotel_rating >= 4.5:
    hotel_price = 2200
elif hotel_rating >= 4:
    hotel_price = 1800
elif hotel_rating >= 3.5:
    hotel_price = 1400
else:
    hotel_price = 1000

hotel_cost = hotel_price * days

# Food cost calculation
food_cost = 0

for food in food_data[:days]:

    rating = food.get("visitor_rating", 4)

    if rating >= 4.5:
        food_price = 200
    elif rating >= 4:
        food_price = 150
    else:
        food_price = 120

    food_cost += food_price * people


# Transport cost (reasonable estimate)
transport_cost = 250 * days

# Attraction cost (many temples are free but we assume small charges)
attraction_cost = 80 * days

# Total cost
total_estimated_cost = hotel_cost + food_cost + transport_cost + attraction_cost

# Example user budget
user_budget = 6000


print("Hotel Cost:", hotel_cost)
print("Food Cost:", food_cost)
print("Transport Cost:", transport_cost)
print("Attraction Cost:", attraction_cost)
print("Total Estimated Cost:", total_estimated_cost)

Hotel Cost: 10800
Food Cost: 4350
Transport Cost: 1500
Attraction Cost: 480
Total Estimated Cost: 17130

In [65]:
adjusted_cost = smart_budget_adjustment(
    total_estimated_cost,
    user_budget,
    hotel_cost,
    food_cost,
    transport_cost,
    attraction_cost
)

===== SMART BUDGET CONTROLLER =====
⚠ Budget exceeded by ₹ 11130

Applying Priority Adjustment...
Hotel downgraded → saved ₹ 3240
Food optimized → saved ₹ 1087
Transport adjusted → saved ₹ 300

Adjusted Package Cost : ₹ 12502

In [66]:
# =========================================
# 🚀 FINAL AI REFINEMENT + UI CONNECTOR
# =========================================

import copy

# ---------------------------------
# 🧠 HELPERS
# ---------------------------------

def flatten_plan(plan):
    places = []
    for day in plan:
        places.extend(plan[day])
    return places


def rebalance_plan(days_keys, places):
    new_plan = {}
    total_days = len(days_keys)

    min_per_day = max(2, len(places) // total_days)

    i = 0
    for day in days_keys:
        new_plan[day] = places[i:i+min_per_day]
        i += min_per_day

    remaining = places[i:]
    idx = 0
    while remaining:
        new_plan[days_keys[idx % total_days]].append(remaining.pop(0))
        idx += 1

    return new_plan


# =========================================
# 💰 REDUCE COST
# =========================================

def reduce_cost_full(plan, hotel, food, transport):

    plan  = copy.deepcopy(plan)
    hotel = copy.deepcopy(hotel)
    food  = copy.deepcopy(food)

    # 🏨 Hotel ↓ 15%
    hotel["price_per_night"] = int(
        hotel.get("price_per_night",
        hotel.get("avg_price_per_night", 800)) * 0.85
    )

    # 🍽️ Food ↓ MAX 3% only (changed from 10%)
    for f in food:
        f["avg_cost_per_person"] = int(
            f.get("avg_cost_per_person", 200) * 0.97
        )

    # 📍 Remove ONLY 1 worst attraction (lowest ai_score)
    all_places = flatten_plan(plan)

    if len(all_places) > 5:
        # Sort ascending by ai_score → worst first
        all_places = sorted(all_places, key=lambda x: x.get("ai_score", 0))
        removed = all_places.pop(0)  # Remove lowest scored
        print(f"💰 Removed: {removed['name']} (AI score: {removed.get('ai_score', 0)})")

    plan = rebalance_plan(list(plan.keys()), all_places)

    return plan, hotel, food, transport


# =========================================
# ⚡ REDUCE FATIGUE
# =========================================

def reduce_fatigue_full(plan, hotel, food, transport):

    plan = copy.deepcopy(plan)
    food = copy.deepcopy(food)

    all_places = flatten_plan(plan)

    if len(all_places) > 5:
        # Sort DESCENDING by fatigue_cost → most tiring first
        all_places = sorted(
            all_places,
            key=lambda x: x.get("fatigue_cost", 0),
            reverse=True
        )
        removed = all_places.pop(0)  # Remove most fatiguing
        print(f"⚡ Removed most tiring: {removed['name']} (Fatigue: {removed.get('fatigue_cost', 0)})")

    # Re-sort remaining by route_cluster → nearby places grouped = less travel
    all_places = sorted(all_places, key=lambda x: x.get("route_cluster", ""))

    plan = rebalance_plan(list(plan.keys()), all_places)

    return plan, hotel, food, transport


# =========================================
# 🌟 BOOST EXPERIENCE
# =========================================

def boost_experience_full(plan, hotel, food, transport):

    plan  = copy.deepcopy(plan)
    hotel = copy.deepcopy(hotel)
    food  = copy.deepcopy(food)

    # 🏨 Hotel upgrade ↑ 20%
    hotel["price_per_night"] = int(
        hotel.get("price_per_night",
        hotel.get("avg_price_per_night", 800)) * 1.2
    )

    # 🍽️ Food upgrade ↑ 20%
    for f in food:
        f["avg_cost_per_person"] = int(
            f.get("avg_cost_per_person", 200) * 1.2
        )

    # 📍 Remove ONLY 1 lowest experience_score attraction
    all_places = flatten_plan(plan)

    if len(all_places) > 5:
        # Sort DESCENDING by experience_score → best first
        all_places = sorted(
            all_places,
            key=lambda x: x.get("experience_score", 0),
            reverse=True
        )
        removed = all_places[-1]   # Last = lowest experience
        all_places = all_places[:-1]
        print(f"🌟 Removed lowest experience: {removed['name']} (Exp: {removed.get('experience_score', 0)})")

    plan = rebalance_plan(list(plan.keys()), all_places)

    return plan, hotel, food, transport


# =========================================
# 🧠 MAIN AI FUNCTION
# =========================================

def run_ai_refinement(action, plan, hotel, food, transport, people, days):

    if action == "reduce_cost":
        return reduce_cost_full(plan, hotel, food, transport)

    elif action == "reduce_fatigue":
        return reduce_fatigue_full(plan, hotel, food, transport)

    elif action == "boost_experience":
        return boost_experience_full(plan, hotel, food, transport)

    return plan, hotel, food, transport


# =========================================
# 🎯 UI HANDLER FUNCTION
# =========================================

def handle_refine(action, plan, hotel, food, transport, people, days):

    new_plan, new_hotel, new_food, new_transport = run_ai_refinement(
        action, plan, hotel, food, transport, people, days
    )

    print("✅ AI refinement applied:", action)

    return new_plan, new_hotel, new_food, new_transport


print("✅ Fixed AI Refinement loaded!")
print("💰 Reduce Cost  → removes lowest AI score attraction + hotel -15% + food -3%")
print("⚡ Reduce Fatigue → removes highest fatigue_cost attraction + clusters by region")
print("🌟 Boost Experience → removes lowest experience_score + hotel +20% + food +20%")

✅ Fixed AI Refinement loaded!
💰 Reduce Cost  → removes lowest AI score attraction + hotel -15% + food -3%
⚡ Reduce Fatigue → removes highest fatigue_cost attraction + clusters by region
🌟 Boost Experience → removes lowest experience_score + hotel +20% + food +20%

In [67]:
# ==============================
# 🔥 RE-OPTIMIZATION ENGINE
# ==============================

import copy

# ------------------------------
# STEP 1: Apply User Changes
# ------------------------------

def apply_user_changes(travel_plan, add_ids=[], remove_ids=[]):

    updated_plan = copy.deepcopy(travel_plan)
    explanations = []

    # Remove attractions
    for rid in remove_ids:
        for day in updated_plan:
            before = len(updated_plan[day])
            updated_plan[day] = [p for p in updated_plan[day] if p["id"] != rid]
            if len(updated_plan[day]) < before:
                explanations.append(f"Removed {rid} as per user request")

    # Add attractions (FIXED - no duplicate)
    for aid in add_ids:

        new_place = next((p for p in attractions if p["id"] == aid), None)

        if new_place:

            # Check duplicate
            existing_ids = []
            for d in updated_plan:
                for p in updated_plan[d]:
                    existing_ids.append(p["id"])

            if aid not in existing_ids:

                new_place = copy.deepcopy(new_place)
                new_place["user_priority"] = "high"

                updated_plan["Day 1"].append(new_place)

                explanations.append(f"Added {new_place['name']} with HIGH priority")

            else:
                explanations.append(f"{new_place['name']} already exists → skipped")

    return updated_plan, explanations


# ------------------------------
# STEP 2: Recalculate Scores
# ------------------------------

def recalculate_scores(plan):

    for day in plan:
        for place in plan[day]:

            experience = place.get("experience_score", 5)
            fatigue = place.get("fatigue_cost", 2)
            time = place.get("avg_visit_time_hours", 1)
            cost = place.get("entry_fee", 0)

            score = (
                experience * 5
                - fatigue * 2
                - time
                - cost * 0.01
            )

            # Boost for user-added places
            if place.get("user_priority") == "high":
                score += 50

            place["priority_score"] = score

    return plan


# ------------------------------
# STEP 3: Remove Low Priority
# ------------------------------

def remove_low_priority(plan, max_hours=8):

    explanations = []

    for day in plan:

        total_time = sum(p.get("avg_visit_time_hours", 1) for p in plan[day])

        while total_time > max_hours:

            sorted_places = sorted(plan[day], key=lambda x: x.get("priority_score", 0))

            removed = None

            for p in sorted_places:
                if p.get("user_priority") != "high":
                    removed = p
                    break

            if removed:
                plan[day].remove(removed)
                explanations.append(f"Removed {removed['name']} due to time constraint")
                total_time -= removed.get("avg_visit_time_hours", 1)
            else:
                break

    return plan, explanations


# ------------------------------
# STEP 4: Gap Filling
# ------------------------------

def fill_gaps(plan):

    explanations = []

    for day in plan:

        total_time = sum(p.get("avg_visit_time_hours", 1) for p in plan[day])

        if total_time < 6:

            for p in attractions:

                if p["id"] not in [x["id"] for x in plan[day]]:

                    if p.get("avg_visit_time_hours", 1) <= 1:

                        plan[day].append(p)
                        explanations.append(f"Added {p['name']} to fill time gap")
                        break

    return plan, explanations


# ------------------------------
# STEP 5: Budget Adjustment
# ------------------------------

def adjust_budget_simple(plan, budget, people):

    explanations = []
    total_cost = 0

    for day in plan:
        for p in plan[day]:
            total_cost += p.get("entry_fee", 0) * people

    if total_cost > budget:

        explanations.append("Budget exceeded → removing low priority attractions")

        for day in plan:

            sorted_places = sorted(plan[day], key=lambda x: x.get("priority_score", 0))

            for p in sorted_places:
                if p.get("user_priority") != "high":
                    plan[day].remove(p)
                    total_cost -= p.get("entry_fee", 0) * people
                    explanations.append(f"Removed {p['name']} to reduce cost")

                    if total_cost <= budget:
                        break

    return plan, explanations


# ------------------------------
# STEP 6: FINAL FUNCTION
# ------------------------------

def reoptimize_trip(travel_plan, add_ids=[], remove_ids=[], budget=5000, people=2):

    print("\n===== 🔥 RE-OPTIMIZATION STARTED =====\n")

    all_explanations = []

    # Step 1
    plan, exp = apply_user_changes(travel_plan, add_ids, remove_ids)
    all_explanations += exp

    # Step 2
    plan = recalculate_scores(plan)

    # Step 3
    plan, exp = remove_low_priority(plan)
    all_explanations += exp

    # Step 4
    plan, exp = fill_gaps(plan)
    all_explanations += exp

    # Step 5
    plan, exp = adjust_budget_simple(plan, budget, people)
    all_explanations += exp

    print("\n===== 🔍 EXPLANATIONS =====\n")
    for e in all_explanations:
        print("•", e)

    print("\n===== ✅ FINAL PLAN =====\n")

    for day in plan:
        print("\n", day)
        for p in plan[day]:
            print(" -", p["name"])

    return plan


    ai_explanation(plan)
    ai_suggestions(plan)
    why_this_plan()
    ai_confidence(plan)

In [68]:
def get_user_customization():

    add_input = input("Enter attraction IDs to ADD (comma separated): ")
    remove_input = input("Enter attraction IDs to REMOVE (comma separated): ")

    add_ids = [x.strip() for x in add_input.split(",") if x]
    remove_ids = [x.strip() for x in remove_input.split(",") if x]

    return add_ids, remove_ids

In [69]:
# ============================================
# 🌄 NASHIK AI TRAVEL PLANNER - COMPLETE UI
# ============================================
!pip install gradio -q

import gradio as gr
import copy
import io
import sys
import time
import json
import math
import re
import traceback
from collections import defaultdict
from datetime import datetime, timedelta

# ============================================
# SAFETY CHECK
# ============================================
try:
    _ = attractions
    _ = hotels
    _ = food
    _ = transport_options
    print("✅ Backend data loaded!")
except NameError as e:
    raise Exception(f"❌ Run backend cells FIRST! Missing: {e}")

try:
    _ = intracity_transport_options
except NameError:
    intracity_transport_options = []
    print("⚠️ intracity_transport_options empty")

# ============================================
# Re-load JSON files
# ============================================
try:
    with open("nashik_food_final_v2.json", "r", encoding="utf-8") as f:
        food_list_for_ui = json.load(f)
    print(f"✅ Food reloaded: {len(food_list_for_ui)} items")
except Exception as e:
    food_list_for_ui = food if isinstance(food, list) else []

try:
    with open("nashik_hotels_final.json", "r", encoding="utf-8") as f:
        hotel_list_for_ui = json.load(f)
    print(f"✅ Hotels reloaded: {len(hotel_list_for_ui)} items")
except Exception as e:
    hotel_list_for_ui = hotels if isinstance(hotels, list) else []

try:
    with open("nashik_transport_final.json", "r", encoding="utf-8") as f:
        transport_list_for_ui = json.load(f)
except Exception as e:
    transport_list_for_ui = transport_options if isinstance(transport_options, list) else []

try:
    with open("nashik_intracity_transport_dataset.json", "r", encoding="utf-8") as f:
        intracity_list_for_ui = json.load(f)
except Exception as e:
    intracity_list_for_ui = intracity_transport_options if isinstance(intracity_transport_options, list) else []

# ============================================
# GLOBAL STATE
# ============================================
APP_STATE = {
    "days": 3, "budget": 30000, "people": 2, "style": "Balanced",
    "traveler_type": "balanced", "food_preference": "veg",
    "hotel_budget": 0, "food_budget": 0, "transport_budget": 0,
    "travel_plan": None, "recommended_hotels": [], "best_transport": None,
    "intracity_transport_data": [],
    "timetable_text": "",
    "package_summary_text": "",
    "package_data": {},
    "current_hotel": None,
    "current_food": [],
    "current_transport": None,
}

# ============================================
# CSS
# ============================================
CUSTOM_CSS = """
.gradio-container { font-family: 'Inter', sans-serif !important; max-width: 1400px !important; }
.hero-section {
    background: linear-gradient(135deg, rgba(102,126,234,0.95), rgba(118,75,162,0.95)),
                url('https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1600');
    background-size: cover; padding: 80px 40px; border-radius: 20px;
    text-align: center; color: white; margin-bottom: 30px;
}
.hero-title { font-size: 56px; font-weight: 800; margin-bottom: 15px; }
.hero-subtitle { font-size: 22px; opacity: 0.95; margin-bottom: 30px; }
.feature-pill {
    display: inline-block; background: rgba(255,255,255,0.2);
    padding: 10px 22px; border-radius: 50px; margin: 6px;
    backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.3);
}
.place-card {
    background: white; border-radius: 16px; overflow: hidden;
    box-shadow: 0 4px 20px rgba(0,0,0,0.08); margin-bottom: 20px; transition: all 0.3s;
}
.place-card:hover { transform: translateY(-4px); box-shadow: 0 12px 30px rgba(0,0,0,0.15); }
.place-content { padding: 18px; }
.place-title { font-size: 18px; font-weight: 700; color: #1a202c; margin-bottom: 8px; }
.place-meta { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 10px; }
.meta-badge { background: #f7fafc; padding: 4px 10px; border-radius: 20px;
    font-size: 12px; color: #4a5568; border: 1px solid #e2e8f0; }
.summary-card { background: linear-gradient(135deg, #667eea, #764ba2);
    color: white; padding: 22px; border-radius: 16px; text-align: center; }
.summary-value { font-size: 28px; font-weight: 800; margin: 6px 0; }
.summary-label { font-size: 12px; opacity: 0.9; text-transform: uppercase; letter-spacing: 1px; }
.day-header { background: linear-gradient(90deg, #667eea, #764ba2); color: white;
    padding: 14px 22px; border-radius: 12px; font-size: 20px; font-weight: 700; margin: 25px 0 15px 0; }
.hotel-card { background: white; border-radius: 16px; padding: 20px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.08); margin-bottom: 15px; border-left: 5px solid #667eea; }
.transport-card { background: linear-gradient(135deg, #f6d365, #fda085);
    color: white; border-radius: 16px; padding: 20px; margin: 15px 0; }
.food-card { background: linear-gradient(135deg, #84fab0, #8fd3f4);
    color: #1a202c; border-radius: 12px; padding: 0; margin: 12px 0;
    overflow: hidden; box-shadow: 0 4px 15px rgba(132,250,176,0.3); transition: all 0.3s; }
.back-btn-bar {
    display: flex; align-items: center; gap: 15px;
    padding: 15px 0; margin-bottom: 20px;
    border-bottom: 2px solid #f0f0f0;
}
@keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.6; transform: scale(1.02); }
}
@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
@keyframes shimmer {
    0% { background-position: -1000px 0; }
    100% { background-position: 1000px 0; }
}
@keyframes float {
    0%, 100% { transform: translateY(0px); }
    50% { transform: translateY(-10px); }
}
@keyframes glow {
    0%, 100% { box-shadow: 0 0 20px rgba(102,126,234,0.5); }
    50% { box-shadow: 0 0 40px rgba(102,126,234,0.8); }
}
@keyframes slideIn {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}
@keyframes timelinePulse {
    0%, 100% { transform: scale(1); box-shadow: 0 0 0 0 rgba(102,126,234,0.4); }
    50% { transform: scale(1.1); box-shadow: 0 0 0 8px rgba(102,126,234,0); }
}
.ai-brain { font-size: 60px; animation: float 2s ease-in-out infinite; display: inline-block; }
.ai-pulse-box { animation: glow 2s ease-in-out infinite; }
.ai-progress-bar { width: 100%; height: 6px; background: rgba(255,255,255,0.2);
    border-radius: 10px; overflow: hidden; margin: 15px 0; }
.ai-progress-fill { height: 100%; background: linear-gradient(90deg, #fff, #84fab0, #fff);
    background-size: 200% 100%; animation: shimmer 1.5s linear infinite; width: 100%; }
.ai-step { display: flex; align-items: center; gap: 12px; padding: 10px 15px; margin: 8px 0;
    background: rgba(255,255,255,0.1); border-radius: 10px; border-left: 3px solid #84fab0;
    animation: pulse 1.5s ease-in-out infinite; }
.ai-dot { width: 8px; height: 8px; border-radius: 50%; background: #84fab0;
    box-shadow: 0 0 10px #84fab0; animation: pulse 1s ease-in-out infinite; }
.summary-stat-card { background: white; border-radius: 16px; padding: 20px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.08); text-align: center; transition: all 0.3s; }
.summary-stat-card:hover { transform: translateY(-5px); box-shadow: 0 10px 25px rgba(0,0,0,0.12); }
.insight-pill { background: white; padding: 12px 18px; border-radius: 12px; margin: 8px 0;
    border-left: 4px solid; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
.timeline-dot { width: 16px; height: 16px; border-radius: 50%;
    animation: timelinePulse 2s ease-in-out infinite; }
footer { visibility: hidden; }
"""

# ============================================
# HELPER
# ============================================
def capture_output(func, *args, **kwargs):
    old_stdout = sys.stdout
    sys.stdout = buffer = io.StringIO()
    try:
        result = func(*args, **kwargs)
    except Exception as e:
        sys.stdout = old_stdout
        return None, f"Error: {e}\n{traceback.format_exc()}"
    sys.stdout = old_stdout
    return result, buffer.getvalue()

def setup_budget(budget, style):
    style_num = {"Budget": 1, "Balanced": 2, "Luxury": 3, "Food Lover": 4}[style]
    if style_num == 1:   h, f, t = 0.4, 0.25, 0.35
    elif style_num == 2: h, f, t = 0.5, 0.25, 0.25
    elif style_num == 3: h, f, t = 0.7, 0.2,  0.1
    else:                h, f, t = 0.4, 0.4,  0.2
    return int(budget * h), int(budget * f), int(budget * t)


# ============================================
# PARSE TIMETABLE → FOOD
# ============================================
def parse_food_from_timetable(timetable_text):
    if not timetable_text:
        return []
    lines      = timetable_text.split("\n")
    food_items = []
    current_day  = ""
    current_time = ""
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("DAY") or (line.startswith("Day") and "---" not in line):
            m = re.search(r"(\d+)", line)
            if m:
                current_day = f"Day {m.group(1)}"
        time_match = re.match(r"(\d{1,2}:\d{2}\s*(?:AM|PM))", line)
        if time_match:
            current_time = time_match.group(1)
        meal_type = None
        meal_name = None
        if line.startswith("Breakfast –") or line.startswith("Breakfast -"):
            meal_type = "Breakfast"
            meal_name = re.split(r"[–-]", line, 1)[-1].strip()
        elif line.startswith("Lunch –") or line.startswith("Lunch -"):
            meal_type = "Lunch"
            meal_name = re.split(r"[–-]", line, 1)[-1].strip()
        elif line.startswith("Dinner –") or line.startswith("Dinner -"):
            meal_type = "Dinner"
            meal_name = re.split(r"[–-]", line, 1)[-1].strip()
        if meal_type and meal_name:
            item = {
                "day": current_day, "time": current_time,
                "meal_type": meal_type, "name": meal_name,
                "famous_for": "", "cost": 0, "duration": 0,
                "category": "", "location": "", "rating": 0,
                "highlight": "", "food_type": "",
            }
            j = i + 1
            while j < len(lines) and j < i + 5:
                nl = lines[j].strip()
                if nl.startswith("Famous For:") or nl.startswith("Famous Dish:"):
                    item["famous_for"] = nl.split(":", 1)[1].strip()
                elif nl.startswith("Cost:"):
                    num = re.search(r"(\d+)", nl)
                    if num: item["cost"] = int(num.group(1))
                elif nl.startswith("Meal Time:") or nl.startswith("Meal Duration:"):
                    num = re.search(r"(\d+)", nl)
                    if num: item["duration"] = int(num.group(1))
                elif nl == "" or nl.startswith("Visit") or nl.startswith("Travel"):
                    break
                j += 1
            for f in food_list_for_ui:
                if f.get("name","").lower() == meal_name.lower():
                    item["category"]  = f.get("category","")
                    item["location"]  = f.get("location_area","")
                    item["rating"]    = f.get("visitor_rating",0)
                    item["highlight"] = f.get("highlight", item["famous_for"])
                    item["food_type"] = f.get("type","")
                    if not item["cost"] and f.get("avg_cost_per_person"):
                        item["cost"]  = f.get("avg_cost_per_person",0)
                    break
            else:
                item["highlight"] = item["famous_for"]
            food_items.append(item)
        i += 1
    return food_items


# ============================================
# 🆕 CALCULATE COSTS DIRECTLY FROM APP_STATE
# ============================================
def calculate_costs_directly():
    """Calculate all costs directly from APP_STATE data"""
    plan      = APP_STATE.get("travel_plan")
    hotel     = APP_STATE["recommended_hotels"][0] if APP_STATE["recommended_hotels"] else None
    transport = APP_STATE["best_transport"]
    people    = APP_STATE["people"]
    days      = APP_STATE["days"]
    budget    = APP_STATE["budget"]

    hotel_cost      = 0
    transport_cost  = 0
    entry_cost      = 0
    food_cost       = 0

    # Hotel cost
    if hotel:
        price    = hotel.get("avg_price_per_night", hotel.get("price_per_night", 0))
        room_cap = hotel.get("max_guests_per_room", 2)
        rooms    = math.ceil(people / max(room_cap, 1))
        hotel_cost = price * rooms * days

    # Transport cost
    if transport:
        cost_type = transport.get("cost_type")
        if cost_type == "per_person":
            transport_cost = transport.get("avg_cost_per_person", 0) * people
        elif cost_type == "per_vehicle":
            transport_cost = (transport.get("fuel_cost_estimate") or 0) + (transport.get("toll_cost") or 0)

    # Entry fees
    if plan:
        entry_cost = sum(
            p.get("entry_fee", 0) for d in plan for p in plan[d]
        ) * people

    # Food cost from timetable
    food_items = parse_food_from_timetable(APP_STATE.get("timetable_text", ""))
    food_cost  = sum(f.get("cost", 0) for f in food_items) * people

    grand_total      = hotel_cost + transport_cost + entry_cost + food_cost
    budget_remaining = budget - grand_total
    utilization      = round((grand_total / budget) * 100, 1) if budget > 0 else 0

    if budget > 0 and grand_total > 0:
        cost_efficiency = round(max(0, 10 - (abs(grand_total - budget) / budget) * 10), 1)
    else:
        cost_efficiency = 5.0

    return {
        "grand_total":      grand_total,
        "hotel_cost":       hotel_cost,
        "transport_cost":   transport_cost,
        "food_cost":        food_cost,
        "entry_cost":       entry_cost,
        "budget_remaining": budget_remaining,
        "utilization_pct":  utilization,
        "cost_efficiency":  cost_efficiency,
    }


# ============================================
# Capture package
# ============================================
def capture_package_with_data(plan, people, days):
    try:
        old_stdout = sys.stdout
        sys.stdout = buffer = io.StringIO()
        try:
            result_dict = generate_travel_package(
                plan, hotel_list_for_ui, food_list_for_ui, people, days,
                budget             = APP_STATE["budget"],
                traveler_type      = APP_STATE["traveler_type"],
                recommended_hotels = APP_STATE["recommended_hotels"],
                best_transport     = APP_STATE["best_transport"],
                food_preference    = APP_STATE["food_preference"]
            )
        except Exception as e:
            sys.stdout = old_stdout
            return f"Error: {e}", {}
        sys.stdout = old_stdout
        return buffer.getvalue(), (result_dict if result_dict else {})
    except Exception as e:
        return f"Error: {e}", {}


# ============================================
# MAIN BACKEND ORCHESTRATOR
# ============================================
def run_full_backend(days, budget, people, style):
    APP_STATE["days"]         = int(days)
    APP_STATE["budget"]       = int(budget)
    APP_STATE["people"]       = int(people)
    APP_STATE["style"]        = style
    APP_STATE["traveler_type"] = {
        "Budget":"budget","Balanced":"balanced",
        "Luxury":"luxury","Food Lover":"budget"
    }[style]

    days_int   = int(days)
    people_int = int(people)

    hb, fb, tb = setup_budget(int(budget), style)
    APP_STATE["hotel_budget"]     = hb
    APP_STATE["food_budget"]      = fb
    APP_STATE["transport_budget"] = tb

    fresh_attractions = copy.deepcopy(attractions)
    for place in fresh_attractions:
        place["ai_score"] = calculate_attraction_score(place)

    fresh_regions = {}
    for place in fresh_attractions:
        region = place.get("route_cluster","Unknown")
        if region not in fresh_regions:
            fresh_regions[region] = []
        fresh_regions[region].append(place)
    for region in fresh_regions:
        fresh_regions[region] = sorted(
            fresh_regions[region], key=lambda x: x.get("ai_score",0), reverse=True
        )

    plan = generate_itinerary(fresh_regions, days_int)
    APP_STATE["travel_plan"] = plan
    print("✅ Itinerary:", {d: len(plan[d]) for d in plan})

    try:
        APP_STATE["recommended_hotels"] = recommend_hotels(
            copy.deepcopy(hotel_list_for_ui), hb, days_int, plan, people_int
        )
    except Exception as e:
        print("⚠️ Hotel error:", e)
        APP_STATE["recommended_hotels"] = []

    try:
        APP_STATE["best_transport"] = recommend_transport_by_region(
            transport_list_for_ui, tb, people_int, APP_STATE["traveler_type"]
        )
    except Exception as e:
        print("⚠️ Transport error:", e)
        APP_STATE["best_transport"] = None

    APP_STATE["intracity_transport_data"] = capture_intracity(
        plan, people_int, APP_STATE["traveler_type"]
    )
    APP_STATE["timetable_text"] = capture_timetable(plan, people_int)
    print("✅ Timetable captured")

    APP_STATE["current_hotel"]     = APP_STATE["recommended_hotels"][0] if APP_STATE["recommended_hotels"] else {}
    APP_STATE["current_food"]      = copy.deepcopy(food_list_for_ui)
    APP_STATE["current_transport"] = APP_STATE["best_transport"]

    pkg_text, pkg_data = capture_package_with_data(plan, people_int, days_int)
    APP_STATE["package_summary_text"] = pkg_text
    APP_STATE["package_data"]         = pkg_data
    print("✅ Package captured")

    return plan


def capture_intracity(plan, people, traveler_type):
    results = []
    intracity_data = intracity_list_for_ui if isinstance(intracity_list_for_ui, list) else []
    if not intracity_data:
        return results
    for day in plan:
        places = plan[day]
        for i in range(len(places) - 1):
            source      = places[i]["name"]
            destination = places[i+1]["name"]
            best_t = None
            best_s = -999
            for t in intracity_data:
                try:
                    if (t.get("source_location","") in source or
                            t.get("destination_location","") in destination):
                        s = calculate_intracity_transport_score(t, people, traveler_type)
                        if s > best_s:
                            best_s = s
                            best_t = t
                except:
                    continue
            if best_t:
                results.append({
                    "day": day, "from": source, "to": destination,
                    "mode":       best_t.get("transport_mode","Auto"),
                    "cost":       best_t.get("avg_cost_per_person",0),
                    "total_cost": best_t.get("avg_cost_per_person",0) * people,
                    "time":       best_t.get("base_travel_time_minutes","N/A"),
                    "score":      round(best_s, 2)
                })
    return results


def capture_timetable(plan, people):
    try:
        result, output = capture_output(
            generate_timetable,
            plan, food_list_for_ui, intracity_list_for_ui, hotel_list_for_ui, people
        )
        return output if output else "No timetable output"
    except Exception as e:
        return f"Error: {e}"


def refresh_all_after_plan_change(plan, people_int):
    try:
        APP_STATE["recommended_hotels"] = recommend_hotels(
            copy.deepcopy(hotel_list_for_ui),
            APP_STATE["hotel_budget"], APP_STATE["days"],
            plan, people_int
        )
        if APP_STATE["recommended_hotels"]:
            APP_STATE["current_hotel"] = APP_STATE["recommended_hotels"][0]
    except: pass
    try:
        APP_STATE["best_transport"] = recommend_transport_by_region(
            transport_list_for_ui, APP_STATE["transport_budget"],
            people_int, APP_STATE["traveler_type"]
        )
        APP_STATE["current_transport"] = APP_STATE["best_transport"]
    except: pass
    APP_STATE["intracity_transport_data"] = capture_intracity(plan, people_int, APP_STATE["traveler_type"])
    APP_STATE["timetable_text"] = capture_timetable(plan, people_int)
    pkg_text, pkg_data = capture_package_with_data(plan, people_int, APP_STATE["days"])
    APP_STATE["package_summary_text"] = pkg_text
    APP_STATE["package_data"]         = pkg_data


# ============================================
# RE-OPTIMIZATION
# ============================================
def reoptimize_using_backend(add_ids=None, remove_ids=None):
    if not APP_STATE["travel_plan"]:
        return None
    add_ids    = add_ids    or []
    remove_ids = remove_ids or []
    try:
        result, output = capture_output(
            reoptimize_trip,
            APP_STATE["travel_plan"],
            add_ids=add_ids, remove_ids=remove_ids,
            budget=APP_STATE["budget"], people=APP_STATE["people"]
        )
        if result:
            APP_STATE["travel_plan"] = result
            refresh_all_after_plan_change(result, APP_STATE["people"])
        return result
    except Exception as e:
        print("Reopt error:", e)
        return APP_STATE["travel_plan"]


# ============================================
# apply_ai_refinement
# ============================================
def apply_ai_refinement(action):
    plan      = APP_STATE.get("travel_plan")
    hotel     = APP_STATE.get("current_hotel") or {}
    food_data = APP_STATE.get("current_food") or copy.deepcopy(food_list_for_ui)
    transport = APP_STATE.get("current_transport")
    people    = APP_STATE.get("people", 2)
    days      = APP_STATE.get("days", 3)

    if not plan:
        return False, "No plan found. Generate a plan first."

    try:
        new_plan, new_hotel, new_food, new_transport = run_ai_refinement(
            action=action, plan=plan, hotel=hotel,
            food=food_data, transport=transport,
            people=people, days=days
        )

        if not new_plan or not any(new_plan.get(d) for d in new_plan):
            return False, "Refinement returned empty plan."

        APP_STATE["travel_plan"]       = new_plan
        APP_STATE["current_hotel"]     = new_hotel
        APP_STATE["current_food"]      = new_food
        APP_STATE["current_transport"] = new_transport

        if new_hotel:
            if APP_STATE["recommended_hotels"]:
                APP_STATE["recommended_hotels"][0] = new_hotel
            else:
                APP_STATE["recommended_hotels"] = [new_hotel]

        refresh_all_after_plan_change(new_plan, people)
        return True, "Success"

    except Exception as e:
        err = traceback.format_exc()
        print(f"⚠️ AI Refinement [{action}] error: {err}")
        return False, str(e)


# ============================================
# RENDER FUNCTIONS
# ============================================
def calc_summary(plan):
    if not plan:
        return 0, 0, 0, 0
    total_places = sum(len(plan[d]) for d in plan)
    total_cost   = sum(p.get("avg_cost_per_person",0) for d in plan for p in plan[d]) * APP_STATE["people"]
    exp_score    = sum(p.get("experience_score",0) for d in plan for p in plan[d])
    avg_exp      = round(exp_score / max(total_places,1), 1)
    fatigue      = sum(p.get("fatigue_cost",0) for d in plan for p in plan[d])
    return total_cost, total_places, avg_exp, fatigue


def render_summary_bar(plan):
    cost, places, exp, fatigue = calc_summary(plan)
    return f"""
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin:20px 0;">
        <div class="summary-card"><div class="summary-label">💰 Total Cost</div>
            <div class="summary-value">₹{cost:,}</div></div>
        <div class="summary-card" style="background:linear-gradient(135deg,#f093fb,#f5576c);">
            <div class="summary-label">📍 Places</div><div class="summary-value">{places}</div></div>
        <div class="summary-card" style="background:linear-gradient(135deg,#4facfe,#00f2fe);">
            <div class="summary-label">⭐ Experience</div><div class="summary-value">{exp}/10</div></div>
        <div class="summary-card" style="background:linear-gradient(135deg,#fa709a,#fee140);">
            <div class="summary-label">⚡ Fatigue</div><div class="summary-value">{fatigue}</div></div>
    </div>"""


# ============================================
# CATEGORY GRADIENTS
# ============================================
CATEGORY_GRADIENTS = {
    "Spiritual": ("linear-gradient(135deg, #f093fb, #f5576c)", "🛕"),
    "Adventure": ("linear-gradient(135deg, #4facfe, #00f2fe)", "🏔️"),
    "Heritage":  ("linear-gradient(135deg, #f6d365, #fda085)", "🏛️"),
    "Cultural":  ("linear-gradient(135deg, #84fab0, #8fd3f4)", "🎭"),
    "Nature":    ("linear-gradient(135deg, #43e97b, #38f9d7)", "🌿"),
    "Scenic":    ("linear-gradient(135deg, #00c6ff, #0072ff)", "🏞️"),
    "Leisure":   ("linear-gradient(135deg, #fa709a, #fee140)", "🍷"),
    "General":   ("linear-gradient(135deg, #667eea, #764ba2)", "📍"),
}


def render_place_card(place):
    name     = place.get('name', '')
    cat      = place.get('category', 'General')
    desc     = place.get('description', '')[:140]
    rating   = place.get('visitor_rating', 4.0)
    location = place.get('location_area', '')
    hours    = place.get('avg_visit_time_hours', 1)
    cost     = place.get('avg_cost_per_person', 0)
    ai_score = place.get('ai_score', 'N/A')
    crowd    = place.get('crowd_level', 'N/A')
    best_t   = place.get('best_time_to_visit', 'Any')
    opening  = place.get('opening_hours', 'N/A')
    gradient, emoji = CATEGORY_GRADIENTS.get(cat, CATEGORY_GRADIENTS["General"])
    return f"""
    <div class="place-card">
        <div style="position:relative;height:200px;background:{gradient};
                    display:flex;align-items:center;justify-content:center;overflow:hidden;">
            <div style="position:absolute;top:-30px;right:-30px;width:120px;height:120px;
                        background:rgba(255,255,255,0.1);border-radius:50%;"></div>
            <div style="position:absolute;bottom:-40px;left:-20px;width:150px;height:150px;
                        background:rgba(255,255,255,0.08);border-radius:50%;"></div>
            <div style="text-align:center;color:white;position:relative;z-index:1;">
                <div style="font-size:50px;line-height:1;">{emoji}</div>
                <div style="font-size:14px;font-weight:700;margin-top:10px;
                            text-shadow:0 2px 4px rgba(0,0,0,0.3);
                            max-width:200px;line-height:1.3;">{name}</div>
            </div>
            <div style="position:absolute;top:12px;left:12px;
                        background:rgba(255,255,255,0.25);color:white;
                        padding:4px 12px;border-radius:20px;font-size:11px;font-weight:700;
                        backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,0.3);">
                {cat}
            </div>
            <div style="position:absolute;top:12px;right:12px;
                        background:rgba(0,0,0,0.5);color:white;
                        padding:4px 10px;border-radius:20px;font-size:12px;font-weight:700;">
                ⭐ {rating}
            </div>
        </div>
        <div class="place-content">
            <div class="place-title">{name}</div>
            <div class="place-meta">
                <span class="meta-badge">📍 {location}</span>
                <span class="meta-badge">⏱ {hours}h</span>
                <span class="meta-badge">💰 ₹{cost}</span>
                <span class="meta-badge">🤖 AI: {ai_score}</span>
            </div>
            <div style="color:#4a5568;font-size:13px;line-height:1.6;">{desc}...</div>
            <div style="margin-top:10px;padding-top:10px;border-top:1px solid #f0f0f0;
                        font-size:12px;color:#718096;display:flex;gap:15px;flex-wrap:wrap;">
                <span>🚦 {crowd}</span>
                <span>🎯 {best_t}</span>
                <span>🕐 {opening}</span>
            </div>
        </div>
    </div>"""


def render_full_plan(plan):
    if not plan:
        return "<p>No plan generated yet.</p>"
    html = render_summary_bar(plan)
    for day_key, places in plan.items():
        day_cost  = sum(p.get("avg_cost_per_person",0) for p in places) * APP_STATE["people"]
        day_hours = sum(p.get("avg_visit_time_hours",1) for p in places)
        html += f'<div class="day-header">📅 {day_key} — {len(places)} places | ⏱ {day_hours}h | 💰 ₹{day_cost:,}</div>'
        if not places:
            html += '<div style="background:#fff3cd;padding:15px;border-radius:8px;color:#856404;margin-bottom:20px;">⚠️ No attractions.</div>'
        else:
            html += '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:18px;">'
            for place in places:
                html += render_place_card(place)
            html += '</div>'
    return html


def render_packages(plan):
    if not plan:
        return "<p>Generate plan first</p>"
    cost, places, exp, fatigue = calc_summary(plan)
    base = cost if cost > 0 else (APP_STATE["budget"] // 2)
    pkgs = [
        ("💸 Budget Plan",   int(base*0.7), places,     "Essential",   "#48bb78", "Basic hotel, local transport"),
        ("⚖️ Balanced Plan", base,          places,     "Recommended", "#667eea", "Mid-range hotel"),
        ("🏨 Premium Plan",  int(base*1.5), places + 2, "Luxury",      "#ed8936", "Premium hotel, private transport"),
    ]
    html = f"""
    <div style="background:white;padding:20px;border-radius:15px;margin-bottom:20px;">
        <h3 style="color:#2d3748;">💼 Your Trip Stats</h3>
        <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:15px;">
            <div style="background:#f7fafc;padding:12px;border-radius:8px;">
                <div style="font-size:12px;color:#718096;">📍 Places</div>
                <div style="font-size:18px;font-weight:700;">{places}</div></div>
            <div style="background:#f7fafc;padding:12px;border-radius:8px;">
                <div style="font-size:12px;color:#718096;">📅 Days</div>
                <div style="font-size:18px;font-weight:700;">{APP_STATE['days']}</div></div>
            <div style="background:#f7fafc;padding:12px;border-radius:8px;">
                <div style="font-size:12px;color:#718096;">⭐ Experience</div>
                <div style="font-size:18px;font-weight:700;">{exp}/10</div></div>
            <div style="background:#f7fafc;padding:12px;border-radius:8px;">
                <div style="font-size:12px;color:#718096;">👥 People</div>
                <div style="font-size:18px;font-weight:700;">{APP_STATE['people']}</div></div>
        </div>
    </div>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:20px 0;">"""
    for title, c, p, level, color, features in pkgs:
        html += f"""
        <div style="background:white;border-radius:20px;padding:25px;
                    box-shadow:0 8px 25px rgba(0,0,0,0.08);border:2px solid {color};text-align:center;">
            <div style="font-size:22px;font-weight:700;color:#2d3748;">{title}</div>
            <div style="color:#718096;margin-top:5px;">{level}</div>
            <div style="font-size:36px;font-weight:800;color:{color};margin:15px 0;">₹{c:,}</div>
            <div style="color:#4a5568;">📍 {p} Places</div>
            <div style="color:#718096;font-size:12px;margin-top:10px;">{features}</div>
        </div>"""
    html += '</div>'
    return html


def render_hotels():
    hotels_list = APP_STATE["recommended_hotels"]
    if not hotels_list:
        return "<p style='padding:20px;'>No hotels found.</p>"
    html = '<h3 style="margin:15px 0;">🏨 Recommended Hotels</h3>'
    for i, h in enumerate(hotels_list, 1):
        price = h.get('avg_price_per_night', h.get('price_per_night', 0))
        html += f"""
        <div class="hotel-card">
            <div style="font-size:18px;font-weight:700;color:#2d3748;">#{i} {h.get('hotel_name','Hotel')}</div>
            <div style="color:#718096;font-size:13px;margin-top:4px;">
                📍 {h.get('area','')} | {h.get('hotel_category','').title()}</div>
            <div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap;">
                <span class="meta-badge">⭐ {h.get('visitor_rating',0)}</span>
                <span class="meta-badge">💰 ₹{price}/night</span>
                <span class="meta-badge">🛏️ Max {h.get('max_guests_per_room',2)} guests</span>
                <span class="meta-badge">🤖 AI: {round(h.get('ai_score',0),1)}</span>
            </div>
            <div style="margin-top:10px;color:#4a5568;font-size:13px;">{h.get('description','')[:150]}...</div>
        </div>"""
    return html


def render_transport():
    html = '<h3 style="margin:15px 0;">🚌 Transport to Nashik</h3>'
    bt = APP_STATE["best_transport"]
    if bt:
        cost_type = bt.get("cost_type")
        if cost_type == "per_person":
            cpp = bt.get("avg_cost_per_person",0)
        elif cost_type == "per_vehicle":
            vc  = (bt.get("fuel_cost_estimate") or 0) + (bt.get("toll_cost") or 0)
            cpp = vc / max(APP_STATE["people"],1)
        else:
            cpp = bt.get("avg_cost_per_person",0)
        html += f"""
        <div class="transport-card">
            <div style="font-size:20px;font-weight:700;">🚐 {bt.get('transport_mode','')}</div>
            <div style="margin-top:10px;">📍 {bt.get('source_location','')} → {bt.get('destination_location','')}</div>
            <div style="margin-top:15px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px;">
                <div><div style="font-size:11px;">PER PERSON</div>
                     <div style="font-size:20px;font-weight:700;">₹{round(cpp,2)}</div></div>
                <div><div style="font-size:11px;">TOTAL</div>
                     <div style="font-size:20px;font-weight:700;">₹{round(cpp*APP_STATE['people'],2)}</div></div>
                <div><div style="font-size:11px;">TIME</div>
                     <div style="font-size:20px;font-weight:700;">{bt.get('base_travel_time_minutes','')} min</div></div>
                <div><div style="font-size:11px;">AI SCORE</div>
                     <div style="font-size:20px;font-weight:700;">{round(bt.get('ai_score',0),1)}</div></div>
            </div>
        </div>"""
    intra = APP_STATE["intracity_transport_data"]
    if intra:
        html += '<h3 style="margin:20px 0 10px 0;">🛺 Intracity Routes</h3>'
        for t in intra:
            html += f"""
            <div style="background:white;padding:15px;border-radius:10px;margin:8px 0;border-left:4px solid #f5576c;">
                <div style="font-weight:700;">{t['from']} → {t['to']}</div>
                <div style="color:#718096;font-size:13px;margin-top:5px;">
                    🚖 {t['mode']} | ₹{t['cost']}/person | ⏱ {t['time']} min</div>
            </div>"""
    return html


def render_food():
    timetable_text = APP_STATE.get("timetable_text","")
    food_items     = parse_food_from_timetable(timetable_text)
    meal_emoji_map = {"Breakfast":"🌅","Lunch":"☀️","Dinner":"🌙"}
    meal_color_map = {
        "Breakfast": "linear-gradient(135deg,#f6d365,#fda085)",
        "Lunch":     "linear-gradient(135deg,#84fab0,#8fd3f4)",
        "Dinner":    "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    }
    html = '<h3 style="margin:15px 0;">🍽️ AI Food Recommendations</h3>'
    html += '<div style="color:#718096;font-size:13px;margin-bottom:15px;">🤖 Food from your AI timetable</div>'
    if not food_items:
        return html + "<p style='padding:20px;color:#c00;'>⚠️ No food found. Generate plan first.</p>"
    days_map = {}
    for item in food_items:
        day = item.get("day","Day 1")
        if day not in days_map:
            days_map[day] = []
        days_map[day].append(item)
    total_meals     = len(food_items)
    total_for_group = sum(f.get("cost",0) for f in food_items) * APP_STATE["people"]
    html += f"""
    <div style="background:linear-gradient(135deg,#f7fafc,#edf2f7);padding:15px 20px;
                border-radius:12px;margin-bottom:20px;display:flex;gap:25px;flex-wrap:wrap;">
        <div style="font-size:13px;color:#4a5568;">🍽️ <strong>{total_meals}</strong> meals planned</div>
        <div style="font-size:13px;color:#4a5568;">💰 Total: <strong>₹{total_for_group:,}</strong>
            <span style="font-size:11px;color:#718096;"> (for {APP_STATE['people']} people)</span></div>
        <div style="font-size:13px;color:#4a5568;">📅 Over <strong>{len(days_map)}</strong> days</div>
    </div>"""
    for day, meals in days_map.items():
        day_cost = sum(m.get("cost",0) for m in meals) * APP_STATE["people"]
        html += f"""
        <div style="background:linear-gradient(90deg,#667eea,#764ba2);color:white;
                    padding:12px 20px;border-radius:12px;margin:20px 0 12px 0;
                    display:flex;justify-content:space-between;align-items:center;font-weight:700;font-size:16px;">
            <span>📅 {day} — {len(meals)} meals</span>
            <span style="font-size:14px;opacity:0.9;">💰 ₹{int(day_cost)}</span>
        </div>"""
        for meal in meals:
            meal_type  = meal.get("meal_type","Meal")
            meal_time  = meal.get("time","")
            name       = meal.get("name","")
            famous_for = meal.get("highlight", meal.get("famous_for",""))
            cost       = meal.get("cost",0)
            total      = cost * APP_STATE["people"]
            duration   = meal.get("duration",0)
            rating     = meal.get("rating",0)
            category   = meal.get("category","")
            location   = meal.get("location","")
            food_type  = meal.get("food_type","")
            emoji      = meal_emoji_map.get(meal_type,"🍴")
            gradient   = meal_color_map.get(meal_type,"linear-gradient(135deg,#84fab0,#8fd3f4)")
            type_badge = ""
            if food_type == "Veg":
                type_badge = '<span style="background:rgba(72,187,120,0.3);color:#1a202c;padding:2px 8px;border-radius:8px;font-size:11px;font-weight:600;">🟢 Veg</span>'
            elif food_type == "Non-Veg":
                type_badge = '<span style="background:rgba(245,87,92,0.3);color:#1a202c;padding:2px 8px;border-radius:8px;font-size:11px;font-weight:600;">🔴 Non-Veg</span>'
            dur_badge = f'<span style="background:rgba(0,0,0,0.1);color:#1a202c;padding:2px 8px;border-radius:8px;font-size:11px;">⏱ {duration} min</span>' if duration else ""
            loc_badge = f'<span style="background:rgba(0,0,0,0.1);color:#1a202c;padding:2px 8px;border-radius:8px;font-size:11px;">📍 {location}</span>' if location else ""
            cat_badge = f'<span style="background:rgba(0,0,0,0.1);color:#1a202c;padding:2px 8px;border-radius:8px;font-size:11px;">{category}</span>' if category else ""
            html += f"""
            <div style="background:{gradient};border-radius:16px;margin:10px 0;overflow:hidden;
                        box-shadow:0 4px 15px rgba(0,0,0,0.08);">
                <div style="background:rgba(0,0,0,0.12);padding:10px 18px;
                            display:flex;justify-content:space-between;align-items:center;">
                    <div style="display:flex;align-items:center;gap:10px;">
                        <span style="font-size:22px;">{emoji}</span>
                        <span style="font-weight:800;color:#1a202c;font-size:15px;">{meal_type}</span>
                        {f'<span style="background:rgba(255,255,255,0.4);color:#1a202c;padding:2px 10px;border-radius:10px;font-size:12px;font-weight:600;">{meal_time}</span>' if meal_time else ''}
                    </div>
                    <div>
                        <span style="font-size:22px;font-weight:900;color:#1a202c;">₹{int(cost)}</span>
                        <span style="font-size:11px;color:#2d3748;margin-left:3px;">/ person</span>
                    </div>
                </div>
                <div style="padding:15px 18px;">
                    <div style="display:flex;justify-content:space-between;align-items:flex-start;">
                        <div style="flex:1;margin-right:15px;">
                            <div style="font-size:20px;font-weight:800;color:#1a202c;margin-bottom:6px;">🍴 {name}</div>
                            <div style="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px;">
                                {type_badge}{cat_badge}{loc_badge}{dur_badge}
                            </div>
                            {f'<div style="font-size:13px;color:#1a202c;font-style:italic;margin-bottom:8px;">✨ {famous_for}</div>' if famous_for else ''}
                            <div style="background:rgba(255,255,255,0.5);display:inline-block;
                                        padding:5px 14px;border-radius:20px;font-size:13px;font-weight:700;color:#1a202c;">
                                👥 Total for {APP_STATE['people']} people: ₹{int(total)}
                            </div>
                        </div>
                        {f'''<div style="text-align:center;background:rgba(255,255,255,0.4);
                                  padding:12px 16px;border-radius:12px;min-width:70px;">
                            <div style="font-size:22px;font-weight:900;color:#1a202c;">⭐</div>
                            <div style="font-size:20px;font-weight:800;color:#1a202c;">{rating}</div>
                            <div style="font-size:10px;color:#2d3748;">rating</div>
                        </div>''' if rating else ''}
                    </div>
                </div>
            </div>"""
    return html


# ============================================
# BEAUTIFUL AI TIMELINE
# ============================================
def render_timetable():
    text = APP_STATE.get("timetable_text", "")
    if not text:
        return "<p>Generate plan first.</p>"

    lines = text.split("\n")
    days_data = []
    current_day = None
    current_entries = []

    for line in lines:
        line_s = line.strip()
        if not line_s:
            continue
        if re.match(r"^DAY\s*\d+", line_s) or (re.match(r"^Day\s*\d+", line_s) and "---" not in line_s):
            if current_day is not None:
                days_data.append((current_day, current_entries))
            m = re.search(r"(\d+)", line_s)
            current_day = f"Day {m.group(1)}" if m else line_s
            current_entries = []
        elif re.match(r"^\d{1,2}:\d{2}\s*(AM|PM)", line_s):
            current_entries.append({"type": "time", "text": line_s})
        elif line_s.startswith("Hotel Check-in"):
            current_entries.append({"type": "hotel", "text": line_s})
        elif any(line_s.startswith(m) for m in ["Breakfast", "Lunch", "Dinner"]):
            current_entries.append({"type": "meal", "text": line_s})
        elif line_s.startswith("Famous For:") or line_s.startswith("Famous Dish:"):
            current_entries.append({"type": "famous", "text": line_s})
        elif line_s.startswith("Cost:"):
            current_entries.append({"type": "cost", "text": line_s})
        elif line_s.startswith("Meal"):
            current_entries.append({"type": "meal_info", "text": line_s})
        elif line_s.startswith("Visit"):
            current_entries.append({"type": "visit", "text": line_s})
        elif line_s.startswith("Travel") or "→" in line_s:
            current_entries.append({"type": "travel", "text": line_s})
        elif line_s.startswith("Description:"):
            current_entries.append({"type": "desc", "text": line_s})
        elif line_s.startswith("Visit Duration:"):
            current_entries.append({"type": "duration", "text": line_s})
        elif line_s.startswith("Stay Cost:") or line_s.startswith("Check-in"):
            current_entries.append({"type": "hotel_info", "text": line_s})
        elif "---" in line_s or "===" in line_s or "AI SMART" in line_s:
            pass
        else:
            current_entries.append({"type": "info", "text": line_s})

    if current_day is not None:
        days_data.append((current_day, current_entries))

    html = f"""
    <div style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;
                padding:40px;border-radius:24px;text-align:center;
                margin-bottom:30px;position:relative;overflow:hidden;
                box-shadow:0 20px 60px rgba(102,126,234,0.3);">
        <div style="position:absolute;top:-40px;right:-40px;width:180px;height:180px;
                    background:rgba(255,255,255,0.08);border-radius:50%;"></div>
        <div style="position:absolute;bottom:-60px;left:-60px;width:220px;height:220px;
                    background:rgba(255,255,255,0.05);border-radius:50%;"></div>
        <div style="position:relative;z-index:1;">
            <div style="font-size:50px;margin-bottom:10px;">📅</div>
            <h1 style="font-size:32px;font-weight:800;margin:0;">AI Smart Travel Timetable</h1>
            <p style="font-size:16px;opacity:0.9;margin-top:8px;">
                🤖 Powered by AI • ⚡ Optimized Schedule • ✨ Day-by-Day Plan
            </p>
            <div style="margin-top:20px;display:inline-flex;gap:12px;flex-wrap:wrap;justify-content:center;">
                <span style="background:rgba(255,255,255,0.2);padding:6px 16px;border-radius:50px;font-size:13px;font-weight:600;">
                    📅 {APP_STATE['days']} Days
                </span>
                <span style="background:rgba(255,255,255,0.2);padding:6px 16px;border-radius:50px;font-size:13px;font-weight:600;">
                    👥 {APP_STATE['people']} People
                </span>
                <span style="background:rgba(255,255,255,0.2);padding:6px 16px;border-radius:50px;font-size:13px;font-weight:600;">
                    📍 Nashik
                </span>
            </div>
        </div>
    </div>
    """

    day_colors = [
        ("#667eea", "#764ba2"), ("#f093fb", "#f5576c"),
        ("#4facfe", "#00f2fe"), ("#43e97b", "#38f9d7"),
        ("#fa709a", "#fee140"), ("#30cfd0", "#330867"),
        ("#a18cd1", "#fbc2eb"),
    ]

    for day_num, (day_label, entries) in enumerate(days_data):
        c1, c2 = day_colors[day_num % len(day_colors)]
        html += f"""
        <div style="margin-bottom:40px;">
            <div style="background:linear-gradient(135deg,{c1},{c2});color:white;
                        padding:20px 30px;border-radius:20px;margin-bottom:25px;
                        box-shadow:0 8px 25px rgba(0,0,0,0.15);
                        display:flex;justify-content:space-between;align-items:center;">
                <div>
                    <div style="font-size:28px;font-weight:800;">📅 {day_label}</div>
                    <div style="font-size:13px;opacity:0.9;margin-top:4px;">🤖 AI Optimized Schedule</div>
                </div>
                <div style="font-size:40px;opacity:0.6;">🗓️</div>
            </div>
            <div style="position:relative;padding-left:40px;">
                <div style="position:absolute;left:16px;top:0;bottom:0;width:3px;
                            background:linear-gradient(180deg,{c1},{c2});
                            border-radius:3px;opacity:0.4;"></div>
        """

        current_time = ""
        i = 0
        while i < len(entries):
            entry = entries[i]
            etype = entry["type"]
            etext = entry["text"]

            if etype == "time":
                current_time = etext
                i += 1
                continue

            if etype == "hotel":
                sub_lines = []
                while i + 1 < len(entries) and entries[i+1]["type"] in ["hotel_info","info","cost"]:
                    i += 1
                    sub_lines.append(entries[i]["text"])
                sub_html = ""
                for sl in sub_lines:
                    if "Stay Cost" in sl or "Cost" in sl:
                        sub_html += f'<div style="color:#667eea;font-weight:700;font-size:13px;margin-top:4px;">💰 {sl}</div>'
                    else:
                        sub_html += f'<div style="color:#718096;font-size:12px;margin-top:3px;">{sl}</div>'
                html += f"""
                <div style="position:relative;margin-bottom:20px;">
                    <div style="position:absolute;left:-32px;top:16px;width:16px;height:16px;
                                border-radius:50%;background:#667eea;
                                box-shadow:0 0 0 4px rgba(102,126,234,0.2);
                                animation:timelinePulse 2s ease-in-out infinite;z-index:1;"></div>
                    {f'<div style="display:inline-block;background:linear-gradient(135deg,{c1},{c2});color:white;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:700;margin-bottom:8px;">{current_time}</div>' if current_time else ''}
                    <div style="background:linear-gradient(135deg,#667eea15,#764ba215);border-radius:16px;padding:18px;
                                border-left:4px solid #667eea;box-shadow:0 4px 15px rgba(0,0,0,0.05);">
                        <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
                            <span style="font-size:24px;">🏨</span>
                            <div style="font-size:16px;font-weight:700;color:#667eea;">{etext}</div>
                        </div>
                        {sub_html}
                    </div>
                </div>"""
                current_time = ""

            elif etype == "meal":
                sub_lines = []
                while i + 1 < len(entries) and entries[i+1]["type"] in ["famous","cost","meal_info","info"]:
                    i += 1
                    sub_lines.append(entries[i])
                famous = ""
                cost_t = ""
                dur_t  = ""
                for sl in sub_lines:
                    if sl["type"] == "famous":
                        famous = sl["text"].replace("Famous For:","").replace("Famous Dish:","").strip()
                    elif sl["type"] == "cost":
                        cost_t = sl["text"].replace("Cost:","").strip()
                    elif sl["type"] == "meal_info":
                        dur_t  = sl["text"]
                icon      = "🌅" if "Breakfast" in etext else ("☀️" if "Lunch" in etext else "🌙")
                meal_grad = "linear-gradient(135deg,#f6d365,#fda085)" if "Breakfast" in etext else \
                            ("linear-gradient(135deg,#84fab0,#8fd3f4)" if "Lunch" in etext else \
                             "linear-gradient(135deg,#a18cd1,#fbc2eb)")
                html += f"""
                <div style="position:relative;margin-bottom:20px;">
                    <div style="position:absolute;left:-32px;top:16px;width:16px;height:16px;
                                border-radius:50%;background:#48bb78;
                                box-shadow:0 0 0 4px rgba(72,187,120,0.2);
                                animation:timelinePulse 2s ease-in-out infinite;z-index:1;"></div>
                    {f'<div style="display:inline-block;background:linear-gradient(135deg,{c1},{c2});color:white;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:700;margin-bottom:8px;">{current_time}</div>' if current_time else ''}
                    <div style="background:{meal_grad};border-radius:16px;padding:18px;overflow:hidden;
                                box-shadow:0 4px 15px rgba(0,0,0,0.08);">
                        <div style="display:flex;justify-content:space-between;align-items:flex-start;">
                            <div>
                                <div style="display:flex;align-items:center;gap:10px;margin-bottom:6px;">
                                    <span style="font-size:24px;">{icon}</span>
                                    <div style="font-size:16px;font-weight:800;color:#1a202c;">{etext}</div>
                                </div>
                                {f'<div style="font-size:13px;color:#2d3748;font-style:italic;margin-bottom:4px;">✨ {famous}</div>' if famous else ''}
                                {f'<div style="font-size:12px;color:#2d3748;opacity:0.8;">{dur_t}</div>' if dur_t else ''}
                            </div>
                            {f'<div style="background:rgba(255,255,255,0.5);padding:8px 14px;border-radius:12px;text-align:center;"><div style="font-size:16px;font-weight:800;color:#1a202c;">💰 {cost_t}</div></div>' if cost_t else ''}
                        </div>
                    </div>
                </div>"""
                current_time = ""

            elif etype == "visit":
                sub_lines = []
                while i + 1 < len(entries) and entries[i+1]["type"] in ["desc","duration","info"]:
                    i += 1
                    sub_lines.append(entries[i])
                desc_t = ""
                dur_t  = ""
                for sl in sub_lines:
                    if sl["type"] == "desc":
                        desc_t = sl["text"].replace("Description:","").strip()[:100]
                    elif sl["type"] == "duration":
                        dur_t  = sl["text"]
                html += f"""
                <div style="position:relative;margin-bottom:20px;">
                    <div style="position:absolute;left:-32px;top:16px;width:16px;height:16px;
                                border-radius:50%;background:#f5576c;
                                box-shadow:0 0 0 4px rgba(245,87,92,0.2);
                                animation:timelinePulse 2s ease-in-out infinite;z-index:1;"></div>
                    {f'<div style="display:inline-block;background:linear-gradient(135deg,{c1},{c2});color:white;padding:4px 14px;border-radius:20px;font-size:12px;font-weight:700;margin-bottom:8px;">{current_time}</div>' if current_time else ''}
                    <div style="background:white;border-radius:16px;padding:18px;
                                border-left:4px solid #f5576c;
                                box-shadow:0 4px 15px rgba(0,0,0,0.06);">
                        <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
                            <span style="font-size:22px;">📍</span>
                            <div style="font-size:16px;font-weight:700;color:#1a202c;">{etext}</div>
                        </div>
                        {f'<div style="font-size:12px;color:#4a5568;line-height:1.5;margin-bottom:6px;">{desc_t}...</div>' if desc_t else ''}
                        {f'<div style="display:inline-block;background:#f7fafc;padding:3px 10px;border-radius:10px;font-size:12px;color:#667eea;font-weight:600;">⏱ {dur_t}</div>' if dur_t else ''}
                    </div>
                </div>"""
                current_time = ""

            elif etype == "travel":
                html += f"""
                <div style="position:relative;margin-bottom:20px;">
                    <div style="position:absolute;left:-32px;top:12px;width:16px;height:16px;
                                border-radius:50%;background:#ed8936;
                                box-shadow:0 0 0 4px rgba(237,137,54,0.2);z-index:1;"></div>
                    <div style="background:linear-gradient(135deg,#fff3e0,#fff8f0);border-radius:12px;
                                padding:12px 16px;border-left:4px solid #ed8936;
                                box-shadow:0 2px 8px rgba(0,0,0,0.04);">
                        <div style="display:flex;align-items:center;gap:10px;">
                            <span style="font-size:18px;">🚖</span>
                            <div style="font-size:14px;color:#ed8936;font-weight:600;">{etext}</div>
                        </div>
                    </div>
                </div>"""
            else:
                if etext and len(etext) > 3 and "===" not in etext and "---" not in etext:
                    html += f"""
                    <div style="position:relative;margin-bottom:12px;">
                        <div style="position:absolute;left:-28px;top:8px;width:10px;height:10px;
                                    border-radius:50%;background:#cbd5e0;z-index:1;"></div>
                        <div style="font-size:12px;color:#718096;padding:6px 0;">{etext}</div>
                    </div>"""
            i += 1

        html += """
            </div>
        </div>"""

    html += """
    <div style="background:linear-gradient(135deg,#84fab0,#8fd3f4);color:#1a202c;
                padding:25px;border-radius:18px;text-align:center;margin-top:20px;">
        <div style="font-size:40px;margin-bottom:8px;">✈️</div>
        <h3 style="margin:0;font-size:20px;font-weight:800;">Your AI Journey Awaits!</h3>
        <p style="margin:8px 0 0;font-size:13px;opacity:0.8;">Every minute planned • AI optimized • Ready to go</p>
    </div>"""

    return html


# ============================================
# 🆕 BEAUTIFUL FINAL SUMMARY — Fixed all zeros
# ============================================
def render_final_summary():
    plan = APP_STATE["travel_plan"]
    pkg  = APP_STATE.get("package_data",{}) or {}
    cost, places, exp, fatigue = calc_summary(plan)

    # 🆕 Always calculate costs directly from APP_STATE
    direct_costs = calculate_costs_directly()

    grand_total      = direct_costs["grand_total"]
    hotel_cost       = direct_costs["hotel_cost"]
    transport_cost   = direct_costs["transport_cost"]
    food_cost        = direct_costs["food_cost"]
    entry_cost       = direct_costs["entry_cost"]
    budget_remaining = direct_costs["budget_remaining"]
    utilization      = direct_costs["utilization_pct"]
    cost_efficiency  = direct_costs["cost_efficiency"]

    # Other stats from pkg (these are fine)
    experience_score  = pkg.get("experience_score", exp)
    fatigue_label     = pkg.get("fatigue_label", "Medium")
    total_attractions = pkg.get("total_attractions", places)
    insights          = pkg.get("insights", [])
    suggestions       = pkg.get("suggestions", [])

    hotel     = APP_STATE["recommended_hotels"][0] if APP_STATE["recommended_hotels"] else None
    transport = APP_STATE["best_transport"]

    # HERO
    html = f"""
    <div style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;
                padding:50px 40px;border-radius:24px;text-align:center;
                margin-bottom:30px;position:relative;overflow:hidden;
                box-shadow:0 20px 60px rgba(102,126,234,0.3);">
        <div style="position:absolute;top:-50px;right:-50px;width:200px;height:200px;
                    background:rgba(255,255,255,0.1);border-radius:50%;"></div>
        <div style="position:absolute;bottom:-80px;left:-80px;width:300px;height:300px;
                    background:rgba(255,255,255,0.05);border-radius:50%;"></div>
        <div style="position:relative;z-index:1;">
            <div style="font-size:60px;margin-bottom:10px;">🎉</div>
            <h1 style="font-size:42px;margin:0;font-weight:800;">Your Trip is Ready!</h1>
            <p style="font-size:20px;opacity:0.95;margin-top:12px;">✨ Smart Nashik AI Travel Package ✨</p>
            <div style="margin-top:25px;display:inline-flex;gap:12px;flex-wrap:wrap;justify-content:center;">
                <span style="background:rgba(255,255,255,0.2);padding:8px 18px;border-radius:50px;font-weight:600;">📍 Nashik</span>
                <span style="background:rgba(255,255,255,0.2);padding:8px 18px;border-radius:50px;font-weight:600;">📅 {APP_STATE['days']} Days</span>
                <span style="background:rgba(255,255,255,0.2);padding:8px 18px;border-radius:50px;font-weight:600;">👥 {APP_STATE['people']} People</span>
                <span style="background:rgba(255,255,255,0.2);padding:8px 18px;border-radius:50px;font-weight:600;">🎯 {APP_STATE['style']}</span>
                <span style="background:rgba(255,255,255,0.2);padding:8px 18px;border-radius:50px;font-weight:600;">🍽️ {APP_STATE['food_preference'].title()}</span>
            </div>
        </div>
    </div>"""

    # KEY STATS
    html += f"""
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-bottom:25px;">
        <div class="summary-stat-card" style="border-top:4px solid #48bb78;">
            <div style="font-size:32px;">💰</div>
            <div style="font-size:11px;color:#718096;text-transform:uppercase;margin-top:5px;letter-spacing:1px;">Grand Total</div>
            <div style="font-size:26px;font-weight:800;color:#2d3748;margin-top:5px;">₹{grand_total:,}</div>
            <div style="font-size:11px;color:#718096;margin-top:5px;">Budget: ₹{APP_STATE['budget']:,}</div>
        </div>
        <div class="summary-stat-card" style="border-top:4px solid #4facfe;">
            <div style="font-size:32px;">⭐</div>
            <div style="font-size:11px;color:#718096;text-transform:uppercase;margin-top:5px;letter-spacing:1px;">Experience</div>
            <div style="font-size:26px;font-weight:800;color:#2d3748;margin-top:5px;">{experience_score}/10</div>
            <div style="font-size:11px;color:#718096;margin-top:5px;">AI quality score</div>
        </div>
        <div class="summary-stat-card" style="border-top:4px solid #f093fb;">
            <div style="font-size:32px;">📍</div>
            <div style="font-size:11px;color:#718096;text-transform:uppercase;margin-top:5px;letter-spacing:1px;">Attractions</div>
            <div style="font-size:26px;font-weight:800;color:#2d3748;margin-top:5px;">{total_attractions}</div>
            <div style="font-size:11px;color:#718096;margin-top:5px;">Places to visit</div>
        </div>
        <div class="summary-stat-card" style="border-top:4px solid #fa709a;">
            <div style="font-size:32px;">⚡</div>
            <div style="font-size:11px;color:#718096;text-transform:uppercase;margin-top:5px;letter-spacing:1px;">Fatigue</div>
            <div style="font-size:20px;font-weight:800;color:#2d3748;margin-top:5px;">{fatigue_label}</div>
            <div style="font-size:11px;color:#718096;margin-top:5px;">Energy demand</div>
        </div>
    </div>"""

    # HOTEL & TRANSPORT
    html += '<div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:25px;">'
    if hotel:
        price = hotel.get('avg_price_per_night', hotel.get('price_per_night', 0))
        html += f"""
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);border-left:5px solid #667eea;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:15px;">
                <div style="font-size:36px;">🏨</div>
                <div>
                    <div style="font-size:11px;color:#718096;text-transform:uppercase;letter-spacing:1px;">Recommended Hotel</div>
                    <div style="font-size:18px;font-weight:800;color:#2d3748;">{hotel.get('hotel_name','N/A')}</div>
                </div>
            </div>
            <div style="background:#f7fafc;padding:15px;border-radius:12px;">
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;">
                    <div><div style="font-size:10px;color:#718096;">📍 LOCATION</div>
                        <div style="font-weight:600;color:#2d3748;font-size:13px;">{hotel.get('area','N/A')}</div></div>
                    <div><div style="font-size:10px;color:#718096;">⭐ RATING</div>
                        <div style="font-weight:600;color:#2d3748;font-size:13px;">{hotel.get('visitor_rating','N/A')}</div></div>
                    <div><div style="font-size:10px;color:#718096;">💰 PER NIGHT</div>
                        <div style="font-weight:600;color:#2d3748;font-size:13px;">₹{price:,}</div></div>
                    <div><div style="font-size:10px;color:#718096;">💵 TOTAL STAY</div>
                        <div style="font-weight:700;color:#48bb78;font-size:14px;">₹{hotel_cost:,}</div></div>
                </div>
            </div>
        </div>"""

    if transport:
        cost_type = transport.get("cost_type")
        if cost_type == "per_person":
            cpp = transport.get("avg_cost_per_person",0)
        elif cost_type == "per_vehicle":
            vc  = (transport.get("fuel_cost_estimate") or 0) + (transport.get("toll_cost") or 0)
            cpp = vc / max(APP_STATE["people"],1)
        else:
            cpp = transport.get("avg_cost_per_person",0)
        html += f"""
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);border-left:5px solid #f6d365;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:15px;">
                <div style="font-size:36px;">🚗</div>
                <div>
                    <div style="font-size:11px;color:#718096;text-transform:uppercase;letter-spacing:1px;">Intercity Transport</div>
                    <div style="font-size:18px;font-weight:800;color:#2d3748;">{transport.get('transport_mode','N/A')}</div>
                </div>
            </div>
            <div style="background:#f7fafc;padding:15px;border-radius:12px;">
                <div style="font-size:11px;color:#718096;margin-bottom:6px;">🗺️ ROUTE</div>
                <div style="font-weight:600;font-size:13px;color:#2d3748;margin-bottom:12px;">
                    {transport.get('source_location','N/A')} → {transport.get('destination_location','N/A')}
                </div>
                <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;">
                    <div><div style="font-size:10px;color:#718096;">⏱ TIME</div>
                        <div style="font-weight:600;color:#2d3748;font-size:13px;">{transport.get('base_travel_time_minutes','N/A')} min</div></div>
                    <div><div style="font-size:10px;color:#718096;">👤 PER PERSON</div>
                        <div style="font-weight:600;color:#2d3748;font-size:13px;">₹{round(cpp)}</div></div>
                    <div><div style="font-size:10px;color:#718096;">💵 TOTAL</div>
                        <div style="font-weight:700;color:#48bb78;font-size:14px;">₹{transport_cost:,}</div></div>
                </div>
            </div>
        </div>"""
    html += '</div>'

    # ATTRACTIONS
    if plan:
        html += """
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);margin-bottom:25px;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px;">
                <div style="font-size:32px;">🗺️</div>
                <div><h3 style="margin:0;color:#2d3748;font-size:20px;">Attractions Covered</h3>
                    <p style="margin:0;color:#718096;font-size:13px;">AI-optimized day-wise plan</p></div>
            </div>"""
        cat_colors = {
            "Spiritual":"#f093fb","Adventure":"#4facfe","Cultural":"#84fab0",
            "Heritage":"#f6d365","Nature":"#48bb78","Scenic":"#00f2fe",
            "Leisure":"#fa709a","General":"#667eea"
        }
        for day, day_places in plan.items():
            day_hours = sum(p.get("avg_visit_time_hours",1) for p in day_places)
            day_entry = sum(p.get("entry_fee",0) for p in day_places) * APP_STATE["people"]
            html += f"""
            <div style="background:linear-gradient(90deg,#667eea15,#764ba215);
                        padding:12px 18px;border-radius:12px;margin-bottom:12px;border-left:4px solid #667eea;">
                <div style="font-weight:700;color:#2d3748;font-size:15px;margin-bottom:8px;">
                    📅 {day} &nbsp;|&nbsp; ⏱ {round(day_hours,1)} hrs &nbsp;|&nbsp; 🎫 Entry: ₹{day_entry}
                </div>
                <div style="display:flex;flex-wrap:wrap;gap:8px;">"""
            for p in day_places:
                cat   = p.get("category","General")
                color = cat_colors.get(cat,"#667eea")
                html += f"""
                <div style="background:white;border:1px solid {color}30;border-left:3px solid {color};
                            border-radius:8px;padding:8px 12px;font-size:12px;">
                    <div style="font-weight:700;color:#2d3748;">{p['name']}</div>
                    <div style="color:#718096;margin-top:2px;">
                        🎫 ₹{p.get('entry_fee',0)} | 🤖 {round(p.get('ai_score',0),1)} | ⚡ {p.get('fatigue_cost',0)}
                    </div>
                </div>"""
            html += '</div></div>'
        html += '</div>'

    # COST BREAKDOWN
    if grand_total > 0:
        html += f"""
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);margin-bottom:25px;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px;">
                <div style="font-size:32px;">💸</div>
                <div><h3 style="margin:0;color:#2d3748;font-size:20px;">Cost Breakdown</h3>
                    <p style="margin:0;color:#718096;font-size:13px;">Where your money goes</p></div>
            </div>
            <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px;">
                <div style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:15px;border-radius:12px;text-align:center;">
                    <div style="font-size:11px;opacity:0.9;">🏨 HOTEL</div>
                    <div style="font-size:20px;font-weight:800;margin-top:5px;">₹{hotel_cost:,}</div>
                    <div style="font-size:11px;opacity:0.85;margin-top:3px;">{round(hotel_cost/grand_total*100,1) if grand_total else 0}%</div>
                </div>
                <div style="background:linear-gradient(135deg,#f6d365,#fda085);color:#1a202c;padding:15px;border-radius:12px;text-align:center;">
                    <div style="font-size:11px;">🚗 TRANSPORT</div>
                    <div style="font-size:20px;font-weight:800;margin-top:5px;">₹{transport_cost:,}</div>
                    <div style="font-size:11px;margin-top:3px;">{round(transport_cost/grand_total*100,1) if grand_total else 0}%</div>
                </div>
                <div style="background:linear-gradient(135deg,#84fab0,#8fd3f4);color:#1a202c;padding:15px;border-radius:12px;text-align:center;">
                    <div style="font-size:11px;">🍽️ FOOD</div>
                    <div style="font-size:20px;font-weight:800;margin-top:5px;">₹{food_cost:,}</div>
                    <div style="font-size:11px;margin-top:3px;">{round(food_cost/grand_total*100,1) if grand_total else 0}%</div>
                </div>
                <div style="background:linear-gradient(135deg,#fa709a,#fee140);color:#1a202c;padding:15px;border-radius:12px;text-align:center;">
                    <div style="font-size:11px;">🎫 ENTRY</div>
                    <div style="font-size:20px;font-weight:800;margin-top:5px;">₹{entry_cost:,}</div>
                    <div style="font-size:11px;margin-top:3px;">{round(entry_cost/grand_total*100,1) if grand_total else 0}%</div>
                </div>
            </div>
            <div style="background:#f7fafc;padding:18px;border-radius:12px;">
                <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
                    <span style="font-size:13px;color:#4a5568;font-weight:600;">Budget Utilization</span>
                    <span style="font-size:13px;color:#4a5568;font-weight:700;">{utilization}%</span>
                </div>
                <div style="background:#e2e8f0;height:14px;border-radius:7px;overflow:hidden;">
                    <div style="background:linear-gradient(90deg,#667eea,#764ba2);
                                width:{min(utilization,100)}%;height:100%;border-radius:7px;"></div>
                </div>
                <div style="display:flex;justify-content:space-between;margin-top:10px;">
                    <span style="font-size:12px;color:#718096;">Spent: <strong style="color:#2d3748;">₹{grand_total:,}</strong></span>
                    <span style="font-size:12px;color:{'#48bb78' if budget_remaining >= 0 else '#e53e3e'};">
                        {'💰 Saved' if budget_remaining >= 0 else '⚠️ Over'}: <strong>₹{abs(budget_remaining):,}</strong>
                    </span>
                </div>
            </div>
        </div>"""

    # AI DASHBOARD
    html += f"""
    <div style="background:linear-gradient(135deg,#1a202c,#2d3748);color:white;
                border-radius:18px;padding:25px;margin-bottom:25px;">
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:20px;">
            <div style="font-size:36px;" class="ai-brain">🤖</div>
            <div><h3 style="margin:0;color:white;font-size:20px;">AI Performance Dashboard</h3>
                <p style="margin:0;color:#a0aec0;font-size:13px;">Neural intelligence metrics</p></div>
        </div>
        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:15px;">
            <div style="background:rgba(255,255,255,0.05);padding:18px;border-radius:12px;border-left:3px solid #84fab0;">
                <div style="font-size:11px;color:#84fab0;text-transform:uppercase;letter-spacing:1px;">💰 Cost Efficiency</div>
                <div style="font-size:32px;font-weight:800;color:white;margin-top:5px;">
                    {cost_efficiency}<span style="font-size:16px;opacity:0.7;">/10</span></div>
                <div style="background:rgba(255,255,255,0.1);height:6px;border-radius:3px;margin-top:10px;overflow:hidden;">
                    <div style="background:#84fab0;width:{min(float(cost_efficiency)*10,100) if cost_efficiency else 0}%;height:100%;"></div>
                </div>
            </div>
            <div style="background:rgba(255,255,255,0.05);padding:18px;border-radius:12px;border-left:3px solid #4facfe;">
                <div style="font-size:11px;color:#4facfe;text-transform:uppercase;letter-spacing:1px;">⭐ Experience Score</div>
                <div style="font-size:32px;font-weight:800;color:white;margin-top:5px;">
                    {experience_score}<span style="font-size:16px;opacity:0.7;">/10</span></div>
                <div style="background:rgba(255,255,255,0.1);height:6px;border-radius:3px;margin-top:10px;overflow:hidden;">
                    <div style="background:#4facfe;width:{min(float(experience_score)*10,100) if experience_score else 0}%;height:100%;"></div>
                </div>
            </div>
            <div style="background:rgba(255,255,255,0.05);padding:18px;border-radius:12px;border-left:3px solid #fa709a;">
                <div style="font-size:11px;color:#fa709a;text-transform:uppercase;letter-spacing:1px;">⚡ Fatigue Level</div>
                <div style="font-size:24px;font-weight:800;color:white;margin-top:5px;">{fatigue_label}</div>
                <div style="font-size:11px;color:#a0aec0;margin-top:8px;">Energy preservation</div>
            </div>
        </div>
    </div>"""

    # INSIGHTS
    if insights:
        html += """
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);margin-bottom:25px;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:18px;">
                <div style="font-size:32px;">💡</div>
                <div><h3 style="margin:0;color:#2d3748;font-size:20px;">AI Insights</h3>
                    <p style="margin:0;color:#718096;font-size:13px;">Smart observations</p></div>
            </div>"""
        colors = ["#667eea","#48bb78","#ed8936","#f5576c","#4facfe"]
        for i, ins in enumerate(insights):
            html += f'<div class="insight-pill" style="border-left-color:{colors[i%len(colors)]};"><span style="color:#2d3748;font-size:14px;">{ins}</span></div>'
        html += '</div>'

    # SUGGESTIONS
    if suggestions:
        html += """
        <div style="background:white;border-radius:18px;padding:25px;
                    box-shadow:0 6px 20px rgba(0,0,0,0.08);margin-bottom:25px;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:18px;">
                <div style="font-size:32px;">🎯</div>
                <div><h3 style="margin:0;color:#2d3748;font-size:20px;">AI Suggestions</h3>
                    <p style="margin:0;color:#718096;font-size:13px;">Improve your plan</p></div>
            </div>"""
        for sug in suggestions:
            html += f"""
            <div style="background:linear-gradient(90deg,#fff5e6,#ffffff);padding:14px 18px;
                        border-radius:12px;margin:10px 0;border-left:4px solid #ed8936;
                        display:flex;align-items:center;gap:12px;">
                <div style="font-size:18px;">✨</div><span style="color:#2d3748;font-size:14px;">{sug}</span>
            </div>"""
        html += '</div>'

    # FOOTER
    html += """
    <div style="background:linear-gradient(135deg,#84fab0,#8fd3f4);color:#1a202c;
                padding:30px;border-radius:18px;text-align:center;margin-top:10px;">
        <div style="font-size:48px;margin-bottom:10px;">🌟</div>
        <h3 style="margin:0;font-size:22px;font-weight:800;">Your Nashik AI Adventure Awaits!</h3>
        <p style="margin:10px 0 0;font-size:14px;opacity:0.85;">Generated by AI • Optimized for you • Ready to explore</p>
    </div>"""
    return html


# ============================================
# NAVIGATION FUNCTIONS
# ============================================
def go_to_chat():
    return gr.update(visible=False), gr.update(visible=True)

def back_to_landing():
    return gr.update(visible=False), gr.update(visible=True)

def back_to_chat():
    return gr.update(visible=False), gr.update(visible=True)

def back_to_packages():
    plan = APP_STATE["travel_plan"]
    packages_content = render_packages(plan) if plan else "<p>No plan yet.</p>"
    return gr.update(visible=False), gr.update(visible=True), packages_content

def go_to_timeline():
    return gr.update(visible=False), gr.update(visible=True), render_timetable()

def go_to_summary():
    return gr.update(visible=False), gr.update(visible=True), render_final_summary()

def back_from_timeline():
    return gr.update(visible=False), gr.update(visible=True), render_full_plan(APP_STATE["travel_plan"])

def back_from_summary():
    return gr.update(visible=False), gr.update(visible=True), render_full_plan(APP_STATE["travel_plan"])


# ============================================
# EVENT HANDLERS
# ============================================
def start_planning(days, budget, people, style, food_pref):
    try:
        APP_STATE["food_preference"] = food_pref
        plan = run_full_backend(days, budget, people, style)
        if plan is None or len(plan) == 0:
            return (gr.update(visible=True), gr.update(visible=False),
                    "<p style='color:red;padding:20px;'>❌ Failed to generate plan.</p>")
        return (gr.update(visible=False), gr.update(visible=True), render_packages(plan))
    except Exception as e:
        err = traceback.format_exc()
        print("🔴 ERROR:", err)
        return (gr.update(visible=True), gr.update(visible=False),
                f"<div style='background:#fee;padding:20px;border-radius:10px;'><pre>{err}</pre></div>")


def view_plan():
    plan = APP_STATE["travel_plan"]
    if not plan:
        return [gr.update()] * 8
    place_choices = [(p["name"],p["id"]) for d in plan for p in plan[d]]
    existing_ids  = {p["id"] for d in plan for p in plan[d]}
    add_choices   = [(a["name"],a["id"]) for a in attractions if a["id"] not in existing_ids]
    return (
        gr.update(visible=False), gr.update(visible=True),
        render_full_plan(plan),
        gr.update(choices=place_choices), gr.update(choices=add_choices),
        render_hotels(), render_transport(), render_food()
    )


# ============================================
# AI THINKING
# ============================================
def show_ai_thinking_advanced(title, steps, color_grad="#667eea, #764ba2"):
    steps_html = ""
    for i, step in enumerate(steps):
        steps_html += f"""
        <div class="ai-step" style="animation-delay:{i*0.2}s;">
            <div class="ai-dot"></div>
            <div style="color:white;font-size:14px;">{step}</div>
        </div>"""
    return f"""
    <div class="ai-pulse-box" style="background:linear-gradient(135deg,{color_grad});
                padding:35px;border-radius:20px;text-align:center;color:white;
                margin:20px 0;position:relative;overflow:hidden;">
        <div style="position:absolute;top:0;left:0;right:0;height:4px;
                    background:linear-gradient(90deg,transparent,white,transparent);
                    background-size:200% 100%;animation:shimmer 2s linear infinite;"></div>
        <div class="ai-brain">🧠</div>
        <div style="font-size:24px;font-weight:800;margin-top:10px;">{title}</div>
        <div class="ai-progress-bar"><div class="ai-progress-fill"></div></div>
        <div style="text-align:left;max-width:500px;margin:20px auto 0;">{steps_html}</div>
        <div style="margin-top:20px;font-size:12px;opacity:0.8;">
            ⚡ Neural network processing • 🎯 Optimizing • ✨ AI learning</div>
    </div>"""


def add_place_with_thinking(place_id):
    if not place_id:
        plan = APP_STATE["travel_plan"]
        pc = [(p["name"],p["id"]) for d in plan for p in plan[d]]
        ei = {p["id"] for d in plan for p in plan[d]}
        ac = [(a["name"],a["id"]) for a in attractions if a["id"] not in ei]
        yield (render_full_plan(plan), gr.update(choices=pc), gr.update(choices=ac),
               render_hotels(), render_transport(), render_food())
        return
    place_name = next((a["name"] for a in attractions if a["id"] == place_id), "attraction")
    yield (
        show_ai_thinking_advanced(f"🤖 Adding {place_name}...",
            [f"📍 Analyzing {place_name}...", "🧮 Recalculating schedule...",
             "🎯 Optimizing order...", "⚡ Finalizing..."], "#667eea, #764ba2"),
        gr.update(), gr.update(),
        show_ai_thinking_advanced("🏨 Re-evaluating Hotels",
            ["🔍 Scanning database...", "📊 Matching preferences...", "💰 Filtering budget..."], "#f093fb, #f5576c"),
        show_ai_thinking_advanced("🚖 Updating Routes",
            ["🗺️ Recalculating paths...", "⏱️ Optimizing slots...", "🚦 Checking traffic..."], "#f6d365, #fda085"),
        show_ai_thinking_advanced("🍽️ Finding Food",
            ["🍴 Matching cuisines...", "⭐ Filtering top-rated...", "💸 Aligning budget..."], "#84fab0, #8fd3f4")
    )
    time.sleep(1.8)
    reoptimize_using_backend(add_ids=[place_id])
    plan = APP_STATE["travel_plan"]
    pc = [(p["name"],p["id"]) for d in plan for p in plan[d]]
    ei = {p["id"] for d in plan for p in plan[d]}
    ac = [(a["name"],a["id"]) for a in attractions if a["id"] not in ei]
    yield (render_full_plan(plan), gr.update(choices=pc, value=None),
           gr.update(choices=ac, value=None), render_hotels(), render_transport(), render_food())


def remove_place_with_thinking(place_id):
    if not place_id:
        plan = APP_STATE["travel_plan"]
        pc = [(p["name"],p["id"]) for d in plan for p in plan[d]]
        ei = {p["id"] for d in plan for p in plan[d]}
        ac = [(a["name"],a["id"]) for a in attractions if a["id"] not in ei]
        yield (render_full_plan(plan), gr.update(choices=pc), gr.update(choices=ac),
               render_hotels(), render_transport(), render_food())
        return
    plan = APP_STATE["travel_plan"]
    place_name = next((p["name"] for d in plan for p in plan[d] if p["id"] == place_id), "attraction")
    yield (
        show_ai_thinking_advanced(f"🤖 Removing {place_name}...",
            [f"📍 Removing {place_name}...", "🔄 Reorganizing...",
             "⏱️ Redistributing slots...", "✨ Finalizing..."], "#f5576c, #f093fb"),
        gr.update(), gr.update(),
        show_ai_thinking_advanced("🏨 Re-checking Hotels",
            ["🔍 Re-scanning...", "📊 Updating..."], "#f093fb, #f5576c"),
        show_ai_thinking_advanced("🚖 Recalculating Routes",
            ["🗺️ Adjusting paths...", "⏱️ Optimizing..."], "#f6d365, #fda085"),
        show_ai_thinking_advanced("🍽️ Updating Food",
            ["🍴 Re-matching...", "⭐ Refreshing..."], "#84fab0, #8fd3f4")
    )
    time.sleep(1.8)
    reoptimize_using_backend(remove_ids=[place_id])
    plan = APP_STATE["travel_plan"]
    pc = [(p["name"],p["id"]) for d in plan for p in plan[d]]
    ei = {p["id"] for d in plan for p in plan[d]}
    ac = [(a["name"],a["id"]) for a in attractions if a["id"] not in ei]
    yield (render_full_plan(plan), gr.update(choices=pc, value=None),
           gr.update(choices=ac, value=None), render_hotels(), render_transport(), render_food())


def refine_reduce_cost():
    plan = APP_STATE.get("travel_plan")
    if not plan:
        yield render_full_plan(plan), render_hotels(), render_transport(), render_food()
        return
    yield (
        show_ai_thinking_advanced("💰 Cost Optimization Mode",
            ["🔍 Scanning all expenses...",
             "📊 Identifying lowest AI-score attraction...",
             "🏨 Reducing hotel price by 15%...",
             "✂️ Removing worst-value attraction...",
             "🍽️ Trimming food costs by 3%..."], "#48bb78, #38a169"),
        show_ai_thinking_advanced("🏨 Adjusting Hotel",
            ["📊 Hotel price -15%...", "💰 Savings applied..."], "#f093fb, #f5576c"),
        show_ai_thinking_advanced("🚖 Transport unchanged",
            ["✅ Transport stays same..."], "#f6d365, #fda085"),
        show_ai_thinking_advanced("🍽️ Food -3%",
            ["🍴 Slight cost reduction...", "💸 Budget meals..."], "#84fab0, #8fd3f4")
    )
    time.sleep(2.0)
    success, msg = apply_ai_refinement("reduce_cost")
    if not success:
        print(f"⚠️ reduce_cost failed: {msg}")
    plan = APP_STATE["travel_plan"]
    yield render_full_plan(plan), render_hotels(), render_transport(), render_food()


def refine_reduce_fatigue():
    plan = APP_STATE.get("travel_plan")
    if not plan:
        yield render_full_plan(plan), render_hotels(), render_transport(), render_food()
        return
    yield (
        show_ai_thinking_advanced("⚡ Fatigue Reduction Mode",
            ["🧠 Scanning fatigue_cost of all attractions...",
             "😓 Finding most tiring attraction...",
             "🗑️ Removing highest fatigue place...",
             "🗺️ Re-clustering by region to reduce travel...",
             "⚖️ Balancing your energy levels..."], "#fa709a, #fee140"),
        show_ai_thinking_advanced("🏨 Hotel unchanged",
            ["✅ No hotel change..."], "#f093fb, #f5576c"),
        show_ai_thinking_advanced("🚖 Routes re-clustered",
            ["🗺️ Nearby places grouped...", "⏱️ Less travel time..."], "#f6d365, #fda085"),
        show_ai_thinking_advanced("🍽️ Food unchanged",
            ["✅ Food stays same..."], "#84fab0, #8fd3f4")
    )
    time.sleep(2.0)
    success, msg = apply_ai_refinement("reduce_fatigue")
    if not success:
        print(f"⚠️ reduce_fatigue failed: {msg}")
    plan = APP_STATE["travel_plan"]
    yield render_full_plan(plan), render_hotels(), render_transport(), render_food()


def refine_boost_experience():
    plan = APP_STATE.get("travel_plan")
    if not plan:
        yield render_full_plan(plan), render_hotels(), render_transport(), render_food()
        return
    yield (
        show_ai_thinking_advanced("🌟 Experience Boost Mode",
            ["⭐ Scanning experience_score of all attractions...",
             "🏨 Upgrading hotel by 20%...",
             "🍽️ Upgrading food quality by 20%...",
             "🏆 Removing lowest experience-score attraction...",
             "✨ Only the best remains!"], "#4facfe, #00f2fe"),
        show_ai_thinking_advanced("🏨 Hotel Upgraded",
            ["⭐ Hotel +20% quality...", "💎 Premium tier..."], "#f093fb, #f5576c"),
        show_ai_thinking_advanced("🚖 Transport unchanged",
            ["✅ Transport stays same..."], "#f6d365, #fda085"),
        show_ai_thinking_advanced("🍽️ Premium Food",
            ["🍴 Food +20% quality...", "⭐ Best options..."], "#84fab0, #8fd3f4")
    )
    time.sleep(2.0)
    success, msg = apply_ai_refinement("boost_experience")
    if not success:
        print(f"⚠️ boost_experience failed: {msg}")
    plan = APP_STATE["travel_plan"]
    yield render_full_plan(plan), render_hotels(), render_transport(), render_food()


def chatbot_respond_with_thinking(message, history):
    if not message:
        yield history, ""
        return
    history.append((message, None))
    history[-1] = (message, "🧠 *Neural network analyzing...* ⚡ Processing... 🎯 Optimizing...")
    yield history, ""
    time.sleep(1.5)
    msg  = message.lower()
    plan = APP_STATE["travel_plan"]
    if "add" in msg and "temple" in msg:
        temples  = [a for a in attractions if a.get("category") == "Spiritual"]
        existing = {p["id"] for d in plan for p in plan[d]} if plan else set()
        new_t    = [t for t in temples if t["id"] not in existing]
        if new_t:
            reoptimize_using_backend(add_ids=[new_t[0]["id"]])
            response = f"✅ Added **{new_t[0]['name']}**!\n\n🤖 *Schedule rebalanced*"
        else:
            response = "All temples already in plan!"
    elif "add" in msg and ("adventure" in msg or "hill" in msg):
        adv      = [a for a in attractions if a.get("category") == "Adventure"]
        existing = {p["id"] for d in plan for p in plan[d]} if plan else set()
        new_adv  = [t for t in adv if t["id"] not in existing]
        if new_adv:
            reoptimize_using_backend(add_ids=[new_adv[0]["id"]])
            response = f"✅ Added **{new_adv[0]['name']}**\n\n🤖 *Adventure mode!*"
        else:
            response = "All adventure spots in plan!"
    elif "reduce cost" in msg or "cheap" in msg or "cost" in msg:
        success, msg_r = apply_ai_refinement("reduce_cost")
        if success:
            plan = APP_STATE["travel_plan"]
            cost, places, _, _ = calc_summary(plan)
            response = f"💰 **Cost Optimized!**\n\n📊 New cost: ₹{cost:,}\n\n🤖 *Hotel -15%, food -3%, worst attraction removed!*"
        else:
            response = f"⚠️ Could not optimize: {msg_r}"
    elif "less crowd" in msg or "crowded" in msg:
        if plan:
            crowded = [(d,p) for d in plan for p in plan[d] if p.get("crowd_level") == "High"]
            if crowded:
                reoptimize_using_backend(remove_ids=[crowded[0][1]["id"]])
                response = f"✅ Removed **{crowded[0][1]['name']}**\n\n🤖 *Low crowd mode!*"
            else:
                response = "Already low-crowd plan!"
        else:
            response = "Generate a plan first!"
    elif "fatigue" in msg or "tired" in msg:
        success, msg_r = apply_ai_refinement("reduce_fatigue")
        if success:
            response = "⚡ **Fatigue Reduced!**\n\nMost tiring attraction removed.\n\n🤖 *Energy saved!*"
        else:
            response = f"⚠️ Could not reduce fatigue: {msg_r}"
    elif "experience" in msg or "boost" in msg or "premium" in msg or "upgrade" in msg:
        success, msg_r = apply_ai_refinement("boost_experience")
        if success:
            response = "🌟 **Experience Boosted!**\n\nHotel +20%, food +20%.\n\n🤖 *Quality maximized!*"
        else:
            response = f"⚠️ Could not boost experience: {msg_r}"
    elif "hotel" in msg:
        if APP_STATE["recommended_hotels"]:
            h     = APP_STATE["recommended_hotels"][0]
            price = h.get('avg_price_per_night', h.get('price_per_night', 0))
            response = f"🏨 **{h['hotel_name']}** — ₹{price}/night | ⭐ {h['visitor_rating']}"
        else:
            response = "No hotel data yet."
    elif "food" in msg:
        food_items = parse_food_from_timetable(APP_STATE.get("timetable_text",""))
        if food_items:
            f        = food_items[0]
            response = f"🍽️ Day 1 {f['meal_type']}: **{f['name']}** — ✨ {f.get('highlight',f.get('famous_for',''))}"
        else:
            response = "No food data yet."
    else:
        response = "💡 Try: 'add temples', 'add adventure', 'reduce cost', 'less crowded', 'reduce fatigue', 'boost experience', 'show hotel', 'show food'"
    history[-1] = (message, response)
    yield history, ""


# ============================================
# BUILD UI
# ============================================
with gr.Blocks(css=CUSTOM_CSS, theme=gr.themes.Soft(primary_hue="purple"), title="Nashik AI Planner") as app:

    with gr.Column(visible=True) as screen_landing:
        gr.HTML("""
        <div class="hero-section">
            <div class="hero-title">🌄 Nashik AI Travel Planner</div>
            <div class="hero-subtitle">🤖 Plan your perfect trip with AI</div>
            <div style="margin-top:30px;">
                <span class="feature-pill">✨ Personalized</span>
                <span class="feature-pill">⚡ Smart Optimization</span>
                <span class="feature-pill">🔄 Real-time</span>
                <span class="feature-pill">🏨 Hotels</span>
                <span class="feature-pill">🚖 Transport</span>
                <span class="feature-pill">🍽️ Food</span>
            </div>
        </div>""")
        with gr.Row():
            gr.HTML("<div></div>")
            start_btn = gr.Button("🚀 Start Planning", size="lg", variant="primary", scale=1)
            gr.HTML("<div></div>")

    with gr.Column(visible=False) as screen_chat:
        with gr.Row():
            back_to_landing_btn = gr.Button("← Back to Home", size="sm", variant="secondary")
            gr.HTML('<div style="flex:1;"></div>')
        gr.HTML("""
        <div style="background:white;padding:30px;border-radius:20px;
                    box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:20px;">
            <div style="display:flex;align-items:center;gap:15px;margin-bottom:20px;">
                <div style="width:50px;height:50px;background:linear-gradient(135deg,#667eea,#764ba2);
                            border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;">🤖</div>
                <div>
                    <div style="font-weight:700;font-size:18px;">AI Travel Assistant</div>
                    <div style="color:#48bb78;font-size:13px;">● Online & Ready</div>
                </div>
            </div>
            <div style="background:#f7fafc;padding:20px;border-radius:12px;">
                👋 Hello! I'll plan your perfect Nashik trip. Share your preferences below:
            </div>
        </div>""")
        with gr.Row():
            with gr.Column():
                gr.Markdown("### 📅 Travel Days")
                days_input = gr.Slider(1, 7, value=3, step=1, label="Days")
            with gr.Column():
                gr.Markdown("### 💰 Budget (₹)")
                budget_input = gr.Slider(5000, 100000, value=30000, step=1000, label="Budget")
        with gr.Row():
            with gr.Column():
                gr.Markdown("### 👥 Travelers")
                people_input = gr.Number(value=2, label="People", minimum=1, maximum=20)
            with gr.Column():
                gr.Markdown("### 🍽️ Food Preference")
                food_pref_input = gr.Radio(["veg","non-veg","both"], value="veg", label="Preference")
        gr.Markdown("### 🎯 Travel Style")
        style_input = gr.Radio(["Budget","Balanced","Luxury","Food Lover"], value="Balanced", label="")
        generate_btn = gr.Button("🤖 Generate My AI Plan", size="lg", variant="primary")

    with gr.Column(visible=False) as screen_packages:
        with gr.Row():
            back_to_chat_btn = gr.Button("← Back to Preferences", size="sm", variant="secondary")
            gr.HTML('<div style="flex:1;"></div>')
        gr.Markdown("# 🎁 Choose Your Travel Package")
        gr.Markdown("AI has crafted these packages based on your preferences")
        packages_html = gr.HTML()
        view_plan_btn = gr.Button("📋 View Detailed Plan →", size="lg", variant="primary")

    with gr.Column(visible=False) as screen_plan:
        with gr.Row():
            back_to_packages_btn = gr.Button("← Back to Packages", size="sm", variant="secondary")
            gr.HTML('<div style="flex:1;display:flex;align-items:center;justify-content:center;">')
            gr.HTML('<span style="font-size:18px;font-weight:700;color:#2d3748;">📋 Your Personalized AI Itinerary</span>')
            gr.HTML('</div><div style="flex:0.3;"></div>')

        with gr.Tabs():
            with gr.Tab("📍 Attractions"): plan_html      = gr.HTML()
            with gr.Tab("🏨 Hotels"):      hotels_html    = gr.HTML()
            with gr.Tab("🚌 Transport"):   transport_html = gr.HTML()
            with gr.Tab("🍽️ Food"):        food_html      = gr.HTML()

        gr.HTML("""
        <div style="background:linear-gradient(135deg,#1a202c,#2d3748);padding:25px;
                    border-radius:20px;margin-top:30px;box-shadow:0 8px 25px rgba(0,0,0,0.15);">
            <div style="display:flex;align-items:center;gap:15px;margin-bottom:15px;">
                <div style="font-size:40px;" class="ai-brain">🧠</div>
                <div>
                    <h2 style="color:white;margin:0;font-size:24px;">🤖 AI Re-Optimization Engine</h2>
                    <p style="color:#a0aec0;margin:5px 0 0;font-size:13px;">
                        Powered by neural intelligence • Real-time learning • Instant adaptation</p>
                </div>
            </div>
            <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:15px;">
                <div style="background:rgba(72,187,120,0.15);padding:15px;border-radius:12px;border-left:3px solid #48bb78;">
                    <div style="color:#48bb78;font-weight:700;font-size:13px;">💰 REDUCE COST</div>
                    <div style="color:#e2e8f0;font-size:12px;margin-top:5px;line-height:1.5;">
                        Hotel -15% • Food -3% • Removes lowest AI score attraction
                    </div>
                </div>
                <div style="background:rgba(250,112,154,0.15);padding:15px;border-radius:12px;border-left:3px solid #fa709a;">
                    <div style="color:#fa709a;font-weight:700;font-size:13px;">⚡ REDUCE FATIGUE</div>
                    <div style="color:#e2e8f0;font-size:12px;margin-top:5px;line-height:1.5;">
                        Removes highest fatigue_cost attraction • Clusters nearby spots
                    </div>
                </div>
                <div style="background:rgba(79,172,254,0.15);padding:15px;border-radius:12px;border-left:3px solid #4facfe;">
                    <div style="color:#4facfe;font-weight:700;font-size:13px;">🌟 BOOST EXPERIENCE</div>
                    <div style="color:#e2e8f0;font-size:12px;margin-top:5px;line-height:1.5;">
                        Hotel +20% • Food +20% • Removes lowest experience_score attraction
                    </div>
                </div>
            </div>
        </div>""")

        gr.Markdown("## 🎯 Refine Your Plan")
        with gr.Row():
            reduce_cost_btn    = gr.Button("💰 Reduce Cost",      variant="secondary", size="lg")
            reduce_fatigue_btn = gr.Button("⚡ Reduce Fatigue",   variant="secondary", size="lg")
            increase_exp_btn   = gr.Button("🌟 Boost Experience", variant="primary",   size="lg")

        with gr.Row():
            with gr.Column():
                gr.Markdown("### ➕ Add Place")
                add_dropdown = gr.Dropdown(choices=[], label="Available Attractions", interactive=True)
                add_btn      = gr.Button("➕ Add to Plan", variant="primary")
            with gr.Column():
                gr.Markdown("### ❌ Remove Place")
                remove_dropdown = gr.Dropdown(choices=[], label="Current Attractions", interactive=True)
                remove_btn      = gr.Button("❌ Remove", variant="stop")

        gr.Markdown("## 🤖 AI Chat Assistant")
        chatbot = gr.Chatbot(height=300, label="Ask anything about your plan")
        with gr.Row():
            chat_input = gr.Textbox(
                placeholder="Try: 'reduce cost', 'reduce fatigue', 'boost experience', 'add temples'",
                scale=4
            )
            chat_send = gr.Button("Send", scale=1, variant="primary")

        with gr.Row():
            timeline_btn = gr.Button("📅 View Timeline", size="lg")
            summary_btn  = gr.Button("🧾 Final Summary", size="lg", variant="primary")

    with gr.Column(visible=False) as screen_timeline:
        with gr.Row():
            back_from_timeline_btn = gr.Button("← Back to Plan", size="sm", variant="secondary")
            gr.HTML('<div style="flex:1;"></div>')
        timeline_html = gr.HTML()

    with gr.Column(visible=False) as screen_summary:
        with gr.Row():
            back_from_summary_btn = gr.Button("← Back to Plan", size="sm", variant="secondary")
            gr.HTML('<div style="flex:1;"></div>')
        summary_html = gr.HTML()

    # ========== EVENT BINDINGS ==========
    start_btn.click(go_to_chat, outputs=[screen_landing, screen_chat])
    back_to_landing_btn.click(back_to_landing, outputs=[screen_chat, screen_landing])
    generate_btn.click(
        start_planning,
        inputs=[days_input, budget_input, people_input, style_input, food_pref_input],
        outputs=[screen_chat, screen_packages, packages_html]
    )
    back_to_chat_btn.click(back_to_chat, outputs=[screen_packages, screen_chat])
    view_plan_btn.click(
        view_plan,
        outputs=[screen_packages, screen_plan, plan_html,
                 remove_dropdown, add_dropdown, hotels_html, transport_html, food_html]
    )
    back_to_packages_btn.click(back_to_packages, outputs=[screen_plan, screen_packages, packages_html])
    add_btn.click(
        add_place_with_thinking, inputs=[add_dropdown],
        outputs=[plan_html, remove_dropdown, add_dropdown, hotels_html, transport_html, food_html]
    )
    remove_btn.click(
        remove_place_with_thinking, inputs=[remove_dropdown],
        outputs=[plan_html, remove_dropdown, add_dropdown, hotels_html, transport_html, food_html]
    )
    reduce_cost_btn.click(refine_reduce_cost, outputs=[plan_html, hotels_html, transport_html, food_html])
    reduce_fatigue_btn.click(refine_reduce_fatigue, outputs=[plan_html, hotels_html, transport_html, food_html])
    increase_exp_btn.click(refine_boost_experience, outputs=[plan_html, hotels_html, transport_html, food_html])
    chat_send.click(
        chatbot_respond_with_thinking,
        inputs=[chat_input, chatbot], outputs=[chatbot, chat_input]
    )
    chat_input.submit(
        chatbot_respond_with_thinking,
        inputs=[chat_input, chatbot], outputs=[chatbot, chat_input]
    )
    timeline_btn.click(go_to_timeline, outputs=[screen_plan, screen_timeline, timeline_html])
    back_from_timeline_btn.click(back_from_timeline, outputs=[screen_timeline, screen_plan, plan_html])
    summary_btn.click(go_to_summary, outputs=[screen_plan, screen_summary, summary_html])
    back_from_summary_btn.click(back_from_summary, outputs=[screen_summary, screen_plan, plan_html])

app.launch(share=True, debug=True)

✅ Backend data loaded!
✅ Food reloaded: 20 items
✅ Hotels reloaded: 20 items

/tmp/ipykernel_12851/4049312165.py:1790: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(css=CUSTOM_CSS, theme=gr.themes.Soft(primary_hue="purple"), title="Nashik AI Planner") as app:
/tmp/ipykernel_12851/4049312165.py:1790: DeprecationWarning: The 'css' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'css' to Blocks.launch() instead.
  with gr.Blocks(css=CUSTOM_CSS, theme=gr.themes.Soft(primary_hue="purple"), title="Nashik AI Planner") as app:
/tmp/ipykernel_12851/4049312165.py:1920: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  chatbot = gr.Chatbot(height=300, label="Ask anything about your plan")
/tmp/ipykernel_12851/4049312165.py:1920: DeprecationWarning: The default value of 'allow_tags' in gr.Chatbot will be changed from False to True in Gradio 6.0. You will need to explicitly set allow_tags=False if you want to disable tags in your chatbot.
  chatbot = gr.Chatbot(height=300, label="Ask anything about your plan")

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://6561775e0145536db6.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

✅ Itinerary: {'Day 1': 2, 'Day 2': 5, 'Day 3': 5}
✅ Timetable captured
✅ Package captured
✅ Itinerary: {'Day 1': 2, 'Day 2': 5, 'Day 3': 5, 'Day 4': 3, 'Day 5': 3}
✅ Timetable captured
✅ Package captured
✅ Itinerary: {'Day 1': 2, 'Day 2': 5, 'Day 3': 5, 'Day 4': 3, 'Day 5': 3}
✅ Timetable captured
✅ Package captured
⚡ Removed most tiring: Brahmagiri Hills (Fatigue: 9)
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://6561775e0145536db6.gradio.live